### ISSUE TITLE
inst support?

### ISSUE THREAD

**Issue by robertzk** [jimhester/covr#10]
Seems it doesn't pick up on stuff in `inst/tests`. All of my packages have tests there per an old comment from Hadley, but this convention might have been deprecated. Should I move all my tests for all of my packages to `tests` off the package root?

**Comment by jimhester** [comment]
I believe that `tests` is the proper directory going forward, however `covr` should still look for tests in `inst/tests` as well to support older packages.  Thank you for opening this issue.

**Comment by robertzk** [comment]
I'm having some trouble running the tests locally, but this will do I think

https://github.com/jimhester/covr/pull/11

**Comment by robertzk** [comment]
https://github.com/jimhester/covr/pull/12

**Comment by jimhester** [comment]
closed via #12
