### ISSUE TITLE
No test coverage on .h files

### ISSUE THREAD

**Issue by hadley** [jimhester/covr#110]
Is this a fundamental limitation, or just a flag you need to flip? When writing C++ in R, often the header files contain a decent amount of code.

**Comment by jimhester** [comment]
Do you have an example with a header that is not just function or class declarations (which won't be covered)?

**Comment by jimhester** [comment]
This might just be as simple as tweaking https://github.com/jimhester/covr/blob/master/R/compiled.R#L108 to include `.h`

**Comment by hadley** [comment]
Here's two:

* https://github.com/hadley/readr/blob/master/src/QiParsers.h
* https://github.com/hadley/readr/blob/master/src/SourceFile.h

**Comment by jimhester** [comment]
Fixed by f0b98681ab43f303286509166fcd363a526682d2
