### ISSUE TITLE
covr with a local jenkins builder

### ISSUE THREAD

**Issue by zachmayer** [jimhester/covr#117]
I'm struggling to use `covr` with my privately-hosted jenkins job builder.  I'm using the following code to generate a `.csv` test coverage report:

``` R
cov <- covr::package_coverage()
write.csv(as.data.frame(cov), file='coverage_report.csv')
```

However, jenkins doesn't know how to parse this .csv.  It turns out jenkins supports a junit-style XML report.  Is there an easy way to turn my `cov` object into a local `XML` file?  

Once I have test coverage locally in the build, I can tell the jenkins server to grab that report post-build.

Thanks!

**Comment by jimhester** [comment]
If you point me to the XML spec jenkins knows how to parse it is possible support it could be added.

However I don't have a jenkins install (or much desire to set one up) so it is going to be difficult for me to test.

I am happy to accept a pull request for this feature though!

**Comment by zachmayer** [comment]
Here's the XML spec: http://help.catchsoftware.com/display/ET/JUnit+Format

I can test the setup.  I was thinking of something like converting the tests to a list, and then converting the list to an XML document using something like this:
http://stackoverflow.com/questions/6256064/how-to-create-xml-from-r-objects-e-g-is-there-a-listtoxml-function

**Comment by zachmayer** [comment]
Here's another doc: http://llg.cubic.org/docs/junit/

I'm trying to write a converter from covr format to a list with the required elements.  Not having a ton of luck so far.

**Comment by zachmayer** [comment]
Ok, here's a start.  Now I just need to figure out the exact structure of the XML and which elements to include for each test case:
```{R}
library(XML)
library(covr)
cov <- package_coverage()

test_list <- lapply(
  cov,
  function(coverage) {
    list(
      "name" = 'a test',
      "classname" = jsonlite::unbox(covr:::display_name(coverage)),
      "status" = coverage$coverage
    )
  })
names(test_list) <- rep('testcase', length(test_list))

res <- list(
  testsuite = list(
    test_list
  )
)

root <- newXMLNode("root")
listToXML <- function(node, sublist){
  for(i in 1:length(sublist)){
    child <- newXMLNode(names(sublist)[i], parent=node);
    
    if (typeof(sublist[[i]]) == "list"){
      listToXML(child, sublist[[i]])
    }
    else{
      xmlValue(child) <- sublist[[i]]
    }
  } 
}
listToXML(root, test_list)
cat(saveXML(root))
```

**Comment by zachmayer** [comment]
hmmm, see also here: https://github.com/floybix/test_that/blob/master/R/reporter-junit.r

**Comment by jimhester** [comment]
I think https://wiki.jenkins-ci.org/display/JENKINS/Cobertura+Plugin is the XML spec we would want to target, that is what is used in [coverage.py](https://github.com/nedbat/coveragepy/blob/f3df4e386979e4a144c46ec8908538182fb94c27/coverage/xmlreport.py) and [gcovr](https://github.com/gcovr/gcovr)

**Comment by zachmayer** [comment]
Sounds good to me!

**Comment by jimhester** [comment]
Junit format is really for storing test results, whereas the Cobertura plugin is for test coverage.  They are similar but distinct ideas.

**Comment by zachmayer** [comment]
I see.  It looks like jenkins also supports [coverage.py style html reports](https://github.com/nedbat/coveragepy/blob/353dff3141e8e0ea3d92ef63f74bcd3729febb42/coverage/html.py)

**Comment by jimhester** [comment]
The Cobertura dtd files are at https://github.com/cobertura/web/tree/master/htdocs/xml, the gcovr implementation to convert is at https://github.com/gcovr/gcovr/blob/master/scripts/gcovr#L1693-L1900.  covr doesn't current track branching, so you can just concentrate on the line counts.

**Comment by zachmayer** [comment]
hmmm, this might be a little beyond my abilities.  I'll see what I can do.

**Comment by zachmayer** [comment]
[Here's an example cobertura xml file](https://raw.githubusercontent.com/jenkinsci/cobertura-plugin/master/src/test/resources/hudson/plugins/cobertura/coverage-with-data.xml)

**Comment by joshkgold** [comment]
Hey @zachmayer, jumping in a little late on this thread.  Did you make any progress with this past this conversation?  I'm ramping up on R, but I do know Jenkins & Cobertura.  And I'm willing to help get something out there.

Thanks!

**Comment by zachmayer** [comment]
@joshkgold I never made any progress here.
