### ISSUE TITLE
Not seeing any markers in RStudio

### ISSUE THREAD

**Issue by briatte** [jimhester/covr#119]
As requested in #43 

In [this package](https://github.com/briatte/ggnetwork), [this test file](https://github.com/briatte/ggnetwork/blob/master/tests/testthat/test-ggnetwork.R) does not test line 104 of [that file](https://github.com/briatte/ggnetwork/blob/master/R/ggnetwork.R). I know that from running `zero_coverage` from the Terminal.

However, when I run `zero_coverage` in RStudio, I do not see any "marker" anywhere on screen:

![screen shot 2015-10-15 at 19 29 06](https://cloud.githubusercontent.com/assets/322533/10522010/1cde5aa0-7373-11e5-9f18-1885825ca4c2.png)

Perhaps I'm just misunderstanding completely how this functionality is supposed to work.

Using RStudio 0.99.486 and `covr` 1.2.3.

**Comment by jimhester** [comment]
Thank you for opening the issue, turns out this was a silly mistake, I never actually called `rstudioapi::sourceMarkers()` previously.

It should work if you update to https://github.com/jimhester/covr/commit/73c13b0730bddb8122e2ae47525ec2a8b4ddf250

**Comment by briatte** [comment]
I now get an empty pane called "Markers", but still no marker for line 104:

![screen shot 2015-10-15 at 20 19 07](https://cloud.githubusercontent.com/assets/322533/10523305/1047813e-737a-11e5-9a4b-9a4056e10894.png)

**Comment by jimhester** [comment]
OK try with 4c1ed31dbc, it should be fixed then.

If not can you give me the output of 

```r
cov <- package_coverage()
as.data.frame(cov)
```

**Comment by briatte** [comment]
Apologies for the delay—I just tried with https://github.com/jimhester/covr/commit/1ac0e8b9ea2e756f2f76b19a17b10f77d8bae93b, and it works perfectly. Thanks!
