### ISSUE TITLE
forcing install of package breaks my use case

### ISSUE THREAD

**Issue by kforner** [jimhester/covr#120]
Hi,

I was using the 0.2 version. I tried to upgrade to the latest master (to be able to set use_subprocess to FALSE), and I'm currently stuck because of the R CMD install stuff.
This requires the package to be installable, in particular that all the dependencies are installed.

The problem is when you develop a collection of interdependent live packages, all dynamically loaded using devtools::load_all(). 

I suppose you have good reasons, probably to avoid the functions to be byte-compiled, but having an option to control this would be nice. or split run_tests() in several public functions, doing only one task:

 - load_package()
 - just_run_tests()
 - process_vignettes()
 - ...

If would allow to use alternate workflows.
I could have a try at a pull request if you want.

Best,
Karl

**Comment by jimhester** [comment]
`devtools::load_all()` doesn't work in all cases (particularly S4 methods have issues) so it cannot be used.

One thing you could do in your case is use `covr::environment_coverage()` directly

```r
env <- devtools::load_all("XXX")
covr::environment_coverage(env$env, covr:::source_dir("XXX/tests", env = new.env(parent=env$env)))
```
However be aware that this is relatively unsupported, and the print methods / display names won't work,  this use case needs additional develpoment work.

Regardless I question the need for using `load_all()`. Can you not use `devtools::install()` on your packages to install the interrelated dependencies?

**Comment by kforner** [comment]
> devtools::load_all() doesn't work in all cases (particularly S4 methods have issues) so it cannot be used.

You mean issues regarding the coverage, or more generally ? 
Do you have pointers on theses issues ? 

> One thing you could do in your case is use covr::environment_coverage() directly
Thanks I'll try that

> Regardless I question the need for using load_all().

>Can you not use devtools::install() on your packages to install the interrelated dependencies?
No, it won't install local source dependencies, as far as I know.
But that's not the point, I have developed a function that installs the dependencies, the problem is that it slows down things a lot, it is much faster to load package from source than installing them, especially when you have 20 such dependencies. 

I know my use case is quite unique, we are developing simultaneously a collection of interdependent packages. The only point I raise is that it was working very fine (for me) with the previous version.
I don't want to get stuck with and old version so I'll try your suggestion, thank you for your time !.

**Comment by kforner** [comment]
> One thing you could do in your case is use covr::environment_coverage() directly

I tried it, it works, but as you told me there are indeed some problems with S4 methods.

So finally I'll use the standard way. Still I'd need more control on the run_tests process, I'll open a new issue for that.
