### ISSUE TITLE
RFE: more control on the way tests are run.

### ISSUE THREAD

**Issue by kforner** [jimhester/covr#121]
I'd need more control on the way the tests are run.

Why would I want more control:
 - to parallelize the tests
 - to monitor tests execution (e.g. with a progress bar)
 - to parametrize  the tests (e.g. having several test suites, or several levels of tests, quick, long...) 

Suggestions on how to do this ? You could modularize the process, e.g.
```
setup <- coverage_setup(pkg)
cov <- coverage_execute(setup, fun = run_tests_standard)
# if needed
coverage <- coverage_finalize(setup, cov)

with run_tests a function with arg (pkg) 
```

Hope it makes sense.

**Comment by jimhester** [comment]
Arbitrary code can be used to run tests by passing expressions to the `...` argument of `package_coverage()`. The default code can be turned off by passing `type="none"`. So you can run your tests is whatever way you wish.

Parallel test execution would require saving coverage results in child processes and communicating them back to the parent process, which while it (might) be possible, is not currently planned. See https://mailman.stat.ethz.ch/pipermail/bioc-devel/2015-August/007904.html for some discussion.

**Comment by kforner** [comment]
>Arbitrary code can be used to run tests by passing expressions to the ... argument of >package_coverage(). The default code can be turned off by passing type="none". So you can run your >tests is whatever way you wish.

Great ! I oversaw this type = "none" thing, sorry.

>Parallel test execution would require saving coverage results in child processes and communicating >them back to the parent process, which while it (might) be possible, is not currently planned

that's what mclapply does, right ?

if you run mclapply AFTER the package instrumentation, executing a single test_file and outputting the results will work, since the forked child will have in-memory the covr package with fresh counters and the instrumented user package. 

The only thing you need after is to merge your results, but from what I read in your code it seems that using c() works, doesn't it ?

**Comment by jimhester** [comment]
This relates to #127 and #126 as well. Once the coverage is aggregated in that fashion it might be possible to do parallel test running.

**Comment by jimhester** [comment]
Parallel testing should now be possible, arbitrary code can be used by setting `type = 'none'` and passing a character vector of the code to run to `code` in `package_coverage()`.

**Comment by wlandau** [comment]
Re: monitoring test execution: what about an option to write to a common log file?
