### ISSUE TITLE
summarize test coverage without coveralls?

### ISSUE THREAD

**Issue by rmflight** [jimhester/covr#13]
Cool package! I noticed that if you run the `package_coverage` function, it gives you a ton of output, that I'm guessing gets uploaded to the *coveralls* service to give you a badge. However, when I'm trying to improve test coverage, I would want to be able to just re-run `package_coverage` as I add tests and see how the coverage changes.

Is there a way to generate a % coverage value from the `package_coverage` output? I'd be willing to write a `summarize` method if I knew how to interpret the values that are being returned.

**Comment by jimhester** [comment]
if you run `as.data.frame(package_coverage())` it will give you a data.frame of the results, which shoud be easier to interpret.

However if all you are after is overall percentage coverage you can just run
```r
cov <- package_coverage()
sum(cov) / length(cov)
```

The value returned by `package_coverage()` is simply a named vector of counts per applicable line.
