### ISSUE TITLE
Rcpp test coverage with c++11

### ISSUE THREAD

**Issue by seninp** [jimhester/covr#131]
I used covr to collect the test coverage for my R/Rcpp code and everything worked just right. But when I bumped to C++ 11 (I need to use unordered maps and few other things), I can no longer get the test coverage for cpp files. Specifically things changed after I added "SystemRequirements: C++11" to my project DESCRIPTION file. Is there any way to see the test coverage for cpp files whilst using C++ 11?

**Comment by jimhester** [comment]
Do you have an example repository where this is failing? It will be easier to diagnose the issue with an concrete example.

**Comment by seninp** [comment]
Thank you! The repository is [jmotif-r](https://github.com/jMotif/jmotif-R). The first build where it didn't collect the coverage is this [e65e3c5](https://codecov.io/github/jMotif/jmotif-R?ref=e65e3c5605bca5202cecbdb7a76c88f7a8f7f7e8) the last success is this one [3792b10](https://codecov.io/github/jMotif/jmotif-R?ref=3792b10f47c91832189e3a388f5805153747fdb3). 

Last days I spent much time tinkering with C++ versions and flags, could be difficult to navigate through commits, sorry.
