### ISSUE TITLE
Take into account code tested in doc examples

### ISSUE THREAD

**Issue by nalimilan** [jimhester/covr#141]
It does not seem that covr takes into account code exercized by examples in documentation, which is run by `R CMD check`. A lot of functions in my package are only tested that way (in particular `print`, `summary`, `plot`...). Would it be possible to include them as if they were tests?

A crude solution would be to parse the `.Rd` files under `man` and put their contents into one file that would be run as a test.

**Comment by jimhester** [comment]
See `package_coverage(type = 'example')`

**Comment by nalimilan** [comment]
Ah, great, sorry for the noise. I would have advocated that `"all"` should be the default, but I guess you've considered that choice.

Though I've not been able to send this data to Coveralls. Doing `Rscript -e 'covr::coveralls(type="all")'` in my Travis CI config file didn't work (Coveralls didn't notice that build):
https://travis-ci.org/nalimilan/logmult/builds/102190513
https://coveralls.io/github/nalimilan/logmult

Great work, BTW! This is really essential to ensure R packages are reliable.

**Comment by jimhester** [comment]
type = 'all' to coveralls isn't going to work. The coverage tools have no notion of different types of coverage. This won't work until https://github.com/jimhester/covr/issues/127 is done and you can merge coverage types together. So at the moment you need to limit to only one type of coverage at a time.

**Comment by nalimilan** [comment]
OK, thanks. So at least filing this issue wasn't totally silly. :-)
