### ISSUE TITLE
package_coverage crashes but tests run fine otherwise

### ISSUE THREAD

**Issue by cdeterman** [jimhester/covr#145]
I have numerous tests in my package, all of which pass when I run `devtools::test()`.  However, when I run `package_coverage(".", type="test")` it crashes with the output:

Any thoughts where I could begin to address this?

> *** caught segfault ***
>address 0xa7fd8f8, cause 'memory not mapped'
>
>Traceback:
> 1: .Call("gpuR_cpp_gpuMatrix_igemm", PACKAGE = "gpuR", ptrA_, ptrB_,     ptrC_, sourceCode_, device_type)
> 2: cpp_gpuMatrix_igemm(A@address, B@address, C@address, kernel,     device_flag)
> 3: gpu_Mat_mult(x, y)
> 4: igpuA %*% igpuB
> 5: igpuA %*% igpuB
> 6: eval(expr, envir, enclos)
> 7: eval(code, new_test_environment)
> 8: withCallingHandlers(eval(code, new_test_environment), error = capture_calls,     message = function(c) invokeRestart("muffleMessage"), warning = function(c) invokeRestart("muffleWarning"))
> 9: doTryCatch(return(expr), name, parentenv, handler)
>10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
>11: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
>12: doTryCatch(return(expr), name, parentenv, handler)
>13: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
>14: tryCatchList(expr, classes, parentenv, handlers)
>15: tryCatch(withCallingHandlers(eval(code, new_test_environment),     error = capture_calls, message = function(c) invokeRestart("muffleMessage"),     warning = function(c) invokeRestart("muffleWarning")), error = function(e) {    ok <- FALSE    report <- expectation_error(e$message, e$calls)    get_reporter()$add_result(report)}, skip = function(e) {    report <- expectation_skipped(e$message)    get_reporter()$add_result(report)})
>16: test_code(desc, substitute(code), env = parent.frame())
>17: test_that("gpuMatrix Integer Matrix multiplication", {    has_gpu_skip()    Cint <- Aint %*% Bint    igpuA <- gpuMatrix(Aint, type = "integer")    igpuB <- gpuMatrix(Bint, type = "integer")    igpuC <- igpuA %*% igpuB    expect_equivalent(igpuC[, ], Cint, info = "integer matrix elements not equivalent")})
>18: eval(expr, envir, enclos)
>19: eval(exprs, envir)
>20: sys.source2(fname, new.env(parent = env))
>21: FUN(X[[i]], ...)
>22: lapply(paths, test_file, env = env, reporter = current_reporter,     start_end_reporter = FALSE)
>23: test_dir(test_path, reporter = reporter, env = env, filter = filter,     ...)
>24: with_top_env(env, {    test_dir(test_path, reporter = reporter, env = env, filter = filter,         ...)})
>25: run_tests(package, test_path, filter, reporter, ...)
>26: test_check("gpuR")
>27: eval(expr, envir, enclos)
>28: eval(exprs[i], envir)
>29: sys.source(file, env)
>30: eval(expr, envir, enclos)
>31: eval(expr, pf)
>32: withVisible(eval(expr, pf))
>33: evalVis(expr)
>34: capture.output(sys.source(file, env))
>35: FUN(X[[i]], ...)
>36: lapply(files, source2, path = path, env = env, quiet = quiet)
>37: source_dir(path = "/home/cdeterman/Documents/gpuR/tests", env = <environment>,     quiet = TRUE)
>38: doTryCatch(return(expr), name, parentenv, handler)
>39: tryCatchOne(expr, names, parentenv, handlers[[1L]])
>40: tryCatchList(expr, classes, parentenv, handlers)
>41: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
>42: try(source_dir(path = "/home/cdeterman/Documents/gpuR/tests",     env = <environment>, quiet = TRUE), silent = TRUE)
>43: eval(expr, envir, enclos)
>44: eval(expr, enc)
>45: environment_coverage_(ns_env, exprs, enc)
>46: force(code)
>47: withr::with_libpaths(tmp_lib, action = "prefix", {    ns_env <- loadNamespace(pkg$package)    env <- new.env(parent = ns_env)    vignette_dir <- file.path(pkg$path, "vignettes")    example_dir <- file.path(pkg$path, "man")    exprs <- c(dots, quote("library(methods)"), if (type == "test" &&         file.exists(testing_dir)) {        if (isTRUE(use_try)) {            bquote(try(source_dir(path = .(testing_dir), env = .(env),                 quiet = .(quiet)), silent = .(quiet)))        } else {            bquote(source_dir(path = .(testing_dir), env = .(env),                 quiet = .(quiet)))        }    } else if (type == "vignette" && file.exists(vignette_dir)) {        sources <- compact(tangle_vignettes(pkg))        lapply(sources, function(file) {            bquote(source2(.(file), .(env), path = .(vignette_dir),                 quiet = .(quiet)))        })    } else if (type == "example" && file.exists(example_dir)) {        ex_file <- process_examples(pkg, tmp_lib, quiet)        if (!is.null(ex_file)) {            bquote(source2(.(ex_file), env = .(env), quiet = .(quiet)))        }    })    enc <- environment()    cov <- environment_coverage_(ns_env, exprs, enc)    try_unload(pkg$package)    cov})
>48: run_tests(pkg, tmp_lib, dots, type, quiet, use_try = use_try)
>49: eval(expr, envir, enclos)
>50: eval(.code)
>51: fun()
>aborting ...
>Segmentation fault (core dumped)

**Comment by jimhester** [comment]
Do your tests pass when you turn off compiler optimisations? e.g. `CFLAGS=-O0`?
