### ISSUE TITLE
Only src/ is covered, R/ is not

### ISSUE THREAD

**Issue by gaborcsardi** [jimhester/covr#148]
I inherited a package on which covr works in a rather strange way. In particular, it picks up the C files in `src`, but not the R files in `R`. Here is the package: 
https://github.com/MangoTheCat/SASxport
https://codecov.io/github/MangoTheCat/SASxport

Any tips on what might cause this and how I could fix it, are welcome. Thanks.

Session info:
```r
> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value
 version  R Under development (unstable) (2016-02-11 r70149)
 system   x86_64, darwin13.4.0
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       Europe/London
 date     2016-02-12

Packages -----------------------------------------------------------------------
 package  * version     date       source
 covr     * 1.3.0       2016-02-12 Github (jimhester/covr@9f4442d)
 devtools   1.10.0.9000 2016-01-28 Github (hadley/devtools@2c08890)
 digest     0.6.9       2016-01-08 CRAN (R 3.2.3)
 lazyeval   0.1.10      2015-01-02 CRAN (R 3.2.0)
 magrittr   1.5         2014-11-22 CRAN (R 3.2.0)
 memoise    1.0.0       2016-01-29 CRAN (R 3.2.3)
 rex        1.0.1       2015-04-28 CRAN (R 3.2.0)
```

**Comment by gaborcsardi** [comment]
Maybe it matters that I ran `covr` on my local machine, because on Travis it fails with this: https://travis-ci.org/MangoTheCat/SASxport/jobs/108901657#L3707

```r
Error: Command ‘'/home/travis/R-bin/R-devel/lib/R/bin/R' '--vanilla' 'CMD' 'INSTALL' '/home/travis/build/MangoTheCat/SASxport' '--no-docs' '--no-multiarch' '--preclean' '--with-keep.source' '--no-byte-compile' '--no-test-load' '--no-multiarch' '-l' '/tmp/Rtmp48V7A8'’ failed (1)
```

**Comment by gaborcsardi** [comment]
The reason was that there was a `q()` in a test file. I am not sure why that messes up `covr`, but apparently it does. 

I am not sure why it fails on Travis, though.

**Comment by jimhester** [comment]
Yeah `q()` in tests is a known issue (https://github.com/jimhester/covr/issues/12).

The way covr works currently is it runs all of your tests, then writes the coverage to a file. If you `q()` from your tests the results never get written to the file (hence you getting no results).

Probably passing `quiet = FALSE` would have shown the same error on your local machine.

I am planning on fixing this as there are a number of packages which use `q()` within their tests, but it is going to require some refactoring to support gracefully which is why it has not been done yet.

**Comment by eddelbuettel** [comment]
I have the same symptom in a package, but not `q()` to cause it.  Very confusing.

Tried to remove/alter a bunch of files, still no R files covered.

Package is digest. Possible interaction with dependencies by covr?

**Comment by eddelbuettel** [comment]
As an update: in my case of the digest package, I (on a whim) made a local bastard copy with using package memoize in covr ... and then all is well and the "bastard covr" can analyse digest just fine.

That is obviously not a great solutions.  Better suggestions, anyone?

**Comment by jimhester** [comment]
The issue was there is a test failing because CRAN R attaches covr.
```r
Error: Failure in `/private/var/folders/dt/r5s12t392tb5sk181j3gs4zw0000gn/T/RtmpiceyMg/R_LIBS4e883dfe0bef/digest/digest-tests/load-unload.Rout.fail`
> ## Test that package can be loaded and unloaded cleanly
>
> dlls0 <- getLoadedDLLs()
> stopifnot(!is.element("digest", loadedNamespaces()),
+           !is.element("digest", names(dlls0)))
>
> loadNamespace("digest")
<environment: namespace:digest>
> dlls1 <- getLoadedDLLs()
> stopifnot(length(dlls1) == length(dlls0) + 1,
+           is.element("digest", names(dlls1)))
Error: length(dlls1) == length(dlls0) + 1 is not TRUE
Execution halted
```
The devel version of covr does not attach digest, so works without issue.

I will schedule a CRAN release to fix this, in the meantime you can install from the github repo if needed.

**Comment by eddelbuettel** [comment]
Nice, will try!
