### ISSUE TITLE
facilitate testing of a single function?

### ISSUE THREAD

**Issue by jennybc** [jimhester/covr#150]
I can use `devtools::test(filter = "foo")` to run tests in matching files.

I'd love to be able to run test files that contain tests that hit a specific function. And it seems like, after computing coverage of a package, `covr`, might actually know which tests hit a specific function. And could generate a list of test files to run. Is this possible (now or in future)?

**Comment by jimhester** [comment]
I don't think this is something that will ever be built into covr as it requires knowing what constitutes an atomic 'test', covr is test framework agnostic.

However you could get this information by running each 'test' separately and using the `functions` columns of `as.data.frame(results)` to gather what functions it tests.

**Comment by jennybc** [comment]
Duly but sadly noted.
