### ISSUE TITLE
Passing user-defined options to testing subprocess

### ISSUE THREAD

**Issue by jackwasey** [jimhester/covr#153]
I'm trying to figure out the best way to pass a flag to my package so I can do slow tests when doing package coverage. I have tried wercker and travis, `options()`, shell environment variables, and have looked through `covr:::run_tests`, and I can't figure this out. I'm now looking at adding expressions to the `package_coverage` command, but will setting an `option` here work? Will setting something in the global environment of the testing process work?

What would you recommend as the best way to pass anything to the package being tested in a subprocess? Thanks.

**Comment by jimhester** [comment]
The best way is probably to use a shell environment variable. Using expressions or setting a global option would also work but you would have to be more careful they were passed appropriately. Shell variables will require the least work and be less prone to error.
