### ISSUE TITLE
Code coverage could include `@examples` lines in source

### ISSUE THREAD

**Issue by jackwasey** [jimhester/covr#157]
It would be interesting to highlight code coverage, not just of functions called by examples (e.g. by `testthat::test_examples()`, but also the roxygen block `@examples` lines themselves. These can form a significant fraction of code in some packages, and although the functions they call are tested and counted in coverage, those lines themselves are not.

**Comment by jimhester** [comment]
This would require a lot of roxygen specific tooling to support. You would have to map the example tests from the generated script to their `.Rd` locations, then map the Rd locations to roxygen comments.

Note there is already support for running coverage for examples directly in covr using the `type` parameter.

I want to keep covr as general as possible and not tie it to any specific framework in general.

**Comment by jackwasey** [comment]
This is definitely in the wish list zone, but when I look at the code coverage reports in `codecov` or `coveralls`, it pains me slightly to see blanks over all the examples. It crossed my mind that `covr` could run the examples directly, and thus know exactly which lines they came from, but would again be dependent on `roxygen` and not an arbitrary R package.
