### ISSUE TITLE
Option to skip gcov checks

### ISSUE THREAD

**Issue by pbreheny** [jimhester/covr#158]
It would be nice to have an option to skip the checks of compiled code.  It's great that covr offers the ability to check compiled code, but these checks often crash for me (they depend on the OS, compiler versions, etc.), so it would be nice if there was an option like use_gcov=FALSE or something to still be able to get coverage even if gcov isn't properly configured to work with covr.

**Comment by jimhester** [comment]
As of 7f7124eb5fb682b257cdf0014ce2c736edc0b8e2 if you set the global option specifying where gcov is found to nothing, `options(covr.gcov = "")` gcov will not run.

**Comment by pbreheny** [comment]
Ah ha!  Thank you very much!
