### ISSUE TITLE
Reading startup files

### ISSUE THREAD

**Issue by gaborcsardi** [jimhester/covr#159]
This is an odd one. I have some active binding definitions in my `.Rprofile`, to ease package development:

```r
makeActiveBinding(".l", function() { devtools::load_all() }, .GlobalEnv)
makeActiveBinding(".i", function() { devtools::install() }, .GlobalEnv)
makeActiveBinding(".d", function() { devtools::document() }, .GlobalEnv)
makeActiveBinding(".b", function() { devtools::build() }, .GlobalEnv)
makeActiveBinding(".c", function() { rcmdcheck::rcmdcheck(".") }, .GlobalEnv)
makeActiveBinding(".t", function() { devtools::test() }, .GlobalEnv)
makeActiveBinding(".r", function() { devtools::reload() }, .GlobalEnv)
makeActiveBinding(".u", function() { devtools::unload() }, .GlobalEnv)
```

When I run `covr::package_coverage()`, it starts firing up the active bindings, I am not quite sure why:

```
✔ 48.9 MiB master
❯ covr::package_coverage(".")
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build '/Users/gaborcsardi/works/falsy'  \
  --no-resave-data --no-manual

* checking for file ‘/Users/gaborcsardi/works/falsy/DESCRIPTION’ ... OK
* preparing ‘falsy’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘falsy_1.0.1.tar.gz’

'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build '/Users/gaborcsardi/works/falsy'  \
  --no-resave-data --no-manual

* checking for file ‘/Users/gaborcsardi/works/falsy/DESCRIPTION’ ... OK
* preparing ‘falsy’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘falsy_1.0.1.tar.gz’

────────────────────────────────────────────────────────────────────────────────
─  using log directory ‘$TMPDIR/RtmpoN0uGD/file181e6e73c7e9/falsy.Rcheck’
─  using R Under development (unstable) (2016-03-04 r70276)
─  using platform: x86_64-apple-darwin13.4.0 (64-bit)
─  using session charset: UTF-8
✔  checking for file ‘falsy/DESCRIPTION’
─  this is package ‘falsy’ version ‘1.0.1’
✔  checking package namespace information
...
```

I think it "calls" `.b` first, then `.c`, etc. Do you have an idea why this could happen? I could just use another startup file when calculating coverage, but it would be nice to avoid having to do this.

Why is `covr::package_coverage` messing with stuff in the global environment?

**Comment by jimhester** [comment]
Putting your active bindings in a `if (interactive()) {}` block should only enable them in interactive processes.

Something must be going wrong if it is doing something in the global environment, it is not intended behavior.

I am currently working on a new version of covr that I am pretty confidant won't exhibit this issue. Once it is in a working state I will ping you to test it to be sure.

As an aside I have a very similar idea in my [Rprofile](https://github.com/jimhester/dotfiles/blob/master/R/Rprofile#L52-L68) for devtools shortcuts. Using active bindings is a good idea though, I had not thought of that!

**Comment by gaborcsardi** [comment]
> Putting your active bindings in a if (interactive()) {} block should only enable them in interactive processes.

That's good. I forgot that covr runs in a separate, non-interactive R process.

Btw. what's the reason for supporting `use_subprocess = FALSE`?

**Comment by gaborcsardi** [comment]
Hmmm, it looks like the `covr` subprocess thinks it is `interactive()`. I have no idea why.

```sh
❯ R -q -e 'print(.c)'
> print(.c)
Error in print(.c) : object '.c' not found
Execution halted

~/works/falsy master*
❯ R -q -e 'covr::package_coverage()'
> covr::package_coverage()
falsy Test Coverage: 93.33%
R/falsy-package.r: 93.33%
>
>
```
So far so good. But
```sh
~/works/falsy master*
❯ R -q
> covr::package_coverage()
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build '/Users/gaborcsardi/works/falsy'  \
  --no-resave-data --no-manual
...
```
starts firing the active bindings again.... anyway, I might just run covr in a non-interactive subprocess.

A side note: we should write a "call out to R" package. Hadley suggested it months ago, and he was absolutely right. It is really hard to get it right....

**Comment by jimhester** [comment]
Yeah I wanted to do that as well (subprocessr, callr) or something. I initially had that code in what became withr but decided it didn't really fit there.

But having good system / calling R functions is definitely something useful so I agree it should be it's own package.

**Comment by gaborcsardi** [comment]
I just wrote a call-out version that uses `pipe()` and calls a callback function on each line of produced output. Which is kinda neat for some applications: https://github.com/MangoTheCat/rcmdcheck/blob/f51b1407b1f0b7bbebad798b2f01ace6db0ea88f/R/safe_system.R#L26-L38

Anyway, this is getting off-topic, so I close it now. But we can write `callr()` next week if we'll have time and nothing better to do. :)

Btw. I am also very interested to hear about the next version of `covr`.

**Comment by jimhester** [comment]
@gaborcsardi This should be fixed in https://github.com/jimhester/covr/tree/v2

That branch should also work with the package you had which called `quit()` within tests, so if you still have that code around it would be good to test it as well.
