### ISSUE TITLE
Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by giuseppec** [jimhester/covr#160]
I am getting the error

```
Error in coveralls() : 
  Failed to upload coverage data. Reply by Coveralls: Couldn't find a repository matching this job.
```
when I use the R package.
This happens after renaming a repo (from https://coveralls.io/github/openml/r to https://coveralls.io/github/openml/openml-r). Also coveralls.io it tells me that the repo has 0% coverage (although bevore the renaming we had 90%, see https://coveralls.io/github/openml/r). What to do in that case?

**Comment by jimhester** [comment]
Did you try syncing with GitHub on coveralls (https://github.com/lemurheavy/coveralls-public/issues/399)

**Comment by giuseppec** [comment]
Yes, I tried syncing and unlinking and linking coveralls with github again but both did not help. Also, when I use `package_coverage()` I get 0% coverage everywhere, which can't be true...

**Comment by jimhester** [comment]
Sure it can you aren't running any tests, you didn't rename the package in your [testthat.R](https://github.com/openml/openml-r/blob/master/tests/testthat.R#L2) file.

**Comment by jimhester** [comment]
Actually scratch that, it isn't the issue, but if you are getting 0 coverage it is likely you aren't running the tests.

**Comment by jimhester** [comment]
And of course you aren't, they have been temporarily disabled (https://github.com/openml/openml-r/commit/c7b9058d907082d6b621348ec5fe988d31cabdbf)

**Comment by kerschke** [comment]
I got the same error message on travis (https://travis-ci.org/kerschke/flacco/jobs/120844311):
```
$ Rscript -e 'covr::coveralls()'
Error in covr::coveralls() : 
  Failed to upload coverage data. Reply by Coveralls: Couldn't find a repository matching this job.
Execution halted
```

I recently had to re-run the tests of my `flacco`-package (which used to produce 100% coverage two months ago), because the `testthat`-package will soon be updated on CRAN and unfortunately comes with interface changes. Apparently `covr` seems to work locally (at least I get 100% coverage for each test)
```{r}
> cv = covr::package_coverage(".")
> cv
flacco Coverage: 100.00%
R/calculateFeatures.R: 100.00%
R/calculateFeatureSet.R: 100.00%
R/cm_computeGridCenters.R: 100.00%
R/cm_convertInitDesignToGrid.R: 100.00%
R/cm_findLinearNeighbours.R: 100.00%
R/cm_findNearestPrototype.R: 100.00%
R/createFeatureObject.R: 100.00%
R/createInitialSample.R: 100.00%
R/feature_cm_angle.R: 100.00%
R/feature_cm_convexity.R: 100.00%
R/feature_cm_gradhomo.R: 100.00%
R/feature_ela_convexity.R: 100.00%
R/feature_ela_curvature.R: 100.00%
R/feature_ela_distribution.R: 100.00%
R/feature_ela_levelset.R: 100.00%
R/feature_ela_local_search.R: 100.00%
R/feature_ela_meta_model.R: 100.00%
R/feature_gcm_barriertree.R: 100.00%
R/feature_gcm.R: 100.00%
R/feature_ic_infocontent.R: 100.00%
R/feature_misc_basic.R: 100.00%
R/feature_misc_dispersion.R: 100.00%
R/feature_misc_linear_model.R: 100.00%
R/feature_misc_nearest_better.R: 100.00%
R/feature_misc_principal_component.R: 100.00%
R/listAvailableFeatures.R: 100.00%
R/measureTime.R: 100.00%
R/plotBarrierTree2D.R: 100.00%
R/plotBarrierTree3D.R: 100.00%
R/plotCellMapping.R: 100.00%
R/plotFeatureImportance.R: 100.00%
R/plotInformationContent.R: 100.00%
R/utilities.R: 100.00%
```
but it's not working on travis and instead throws the aforementioned error.

Do you have any suggestions how I could solve that problem (cf. https://github.com/kerschke/flacco/issues/23) or at least what might cause those problems?

**Comment by kerschke** [comment]
Hmm.. after restarting the build on travis, it looks quite ok:
```
$ Rscript -e 'covr::coveralls()'
$message
[1] "Job #145.1"

$url
[1] "https://coveralls.io/jobs/13407909"

after_success.2
40.80s

$ Rscript -e 'covr::codecov()'
$meta
$meta$status
[1] 200

$id
[1] "upload:2314:8017213d42dc674c9b7a5ab7486460361794a088:145.1:4820:1460062967.54"

$uploaded
[1] TRUE

$queued
[1] TRUE

$url
[1] "http://codecov.io/github/kerschke/flacco?ref=8017213d42dc674c9b7a5ab7486460361794a088"

$message
[1] "Coverage reports upload successfully"
```

However, the uploaded coverage still is 33.3% although it is locally at 100% (and used to be 100% two months ago).
@jimhester Do you have any ideas what's going wrong here?

**Comment by jimhester** [comment]
What version of covr are you running locally? What version on travis?

**Comment by kerschke** [comment]
2.0.1 locally and probably the same version on travis (at least I'm loading the github version on travis).

**Comment by jimhester** [comment]
I am not sure what is going on either, I also get 100% test coverage locally. You could try running the coverage separately first, printing it, then passing to the coverage services. You probably want to do that anyway to avoid having to run your tests twice.

```yaml
after_success:
  - Rscript -e '(cov <- covr::package_coverage())' -e 'covr::codecov(coverage = cov)' -e 'covr::coveralls(coverage = cov)'

**Comment by kerschke** [comment]
Good idea. I just ran it with your suggestion and the resulting coverage is the same as the one that is shown online (and not the same as I receive locally):
```
$ Rscript -e '(cov <- covr::package_coverage())' -e 'covr::codecov(coverage = cov)' -e 'covr::coveralls(coverage = cov)'
flacco Coverage: 33.09%
R/calculateFeatures.R: 0.00%
R/createInitialSample.R: 0.00%
R/feature_gcm_barriertree.R: 0.00%
R/feature_gcm.R: 0.00%
R/feature_ic_infocontent.R: 0.00%
R/feature_misc_basic.R: 0.00%
R/feature_misc_dispersion.R: 0.00%
R/feature_misc_linear_model.R: 0.00%
R/feature_misc_nearest_better.R: 0.00%
R/feature_misc_principal_component.R: 0.00%
R/plotBarrierTree2D.R: 0.00%
R/plotBarrierTree3D.R: 0.00%
R/plotCellMapping.R: 0.00%
R/plotFeatureImportance.R: 0.00%
R/plotInformationContent.R: 0.00%
R/createFeatureObject.R: 64.20%
R/feature_ela_levelset.R: 67.57%
R/cm_computeGridCenters.R: 72.00%
R/utilities.R: 76.47%
R/cm_convertInitDesignToGrid.R: 81.25%
R/cm_findLinearNeighbours.R: 87.76%
R/cm_findNearestPrototype.R: 92.00%
R/calculateFeatureSet.R: 100.00%
R/feature_cm_angle.R: 100.00%
R/feature_cm_convexity.R: 100.00%
R/feature_cm_gradhomo.R: 100.00%
R/feature_ela_convexity.R: 100.00%
R/feature_ela_curvature.R: 100.00%
R/feature_ela_distribution.R: 100.00%
R/feature_ela_local_search.R: 100.00%
R/feature_ela_meta_model.R: 100.00%
R/listAvailableFeatures.R: 100.00%
R/measureTime.R: 100.00%
```
