### ISSUE TITLE
Problem checking coverage in switch statments & work around

### ISSUE THREAD

**Issue by tom-n-pdx** [jimhester/covr#163]
In the released and github version of covr I had a problem checking coverage in switch statements. I found a simple work around.

I have a switch that selects based on a string. The different choices are all marked covered even if they are not.

Here is a small example of the code:

```R
switch(slot,
    modelname = name.lp(lprec, name=value),
    modelsense = lp.control(lprec, sense=value),
    obj = set.objfn(lprec, rep_len(value, ncol)),
    lb = set.bounds(lprec, lower = rep_len(value, ncol))
    )
```

I am only testing one of the slots values but all are marked as covered.

The work around that solved the problem for me was to surround each switch selection with { }'s, e.g.

`modelname   = { name.lp(lprec, name=value)},`

This solved the problem and gave me correct coverage numbers.

**Comment by jimhester** [comment]
This is really an extension of #39 (with the same workaround).
