### ISSUE TITLE
Incorrect coverage in C++ header files

### ISSUE THREAD

**Issue by Enchufa2** [jimhester/covr#164]
Since the last release (v2.0.1), I noticed that `.h` files are now analysed too. But I'm pretty sure that all lines reported as _not covered_ in my project (check [this build](https://coveralls.io/builds/5686985)) are in fact covered. 

For instance, a very clear example: [this line](https://coveralls.io/builds/5686985/source?filename=src%2Fentity.h#L27) is reported as _not covered_. However, [this line](https://coveralls.io/builds/5686985/source?filename=src%2Fentity.h#L354), reported as _covered_ in the very same file, calls the latter (!).

**Comment by jimhester** [comment]
That function is inline which is likely why it was not tracked. You would probably have to explicitly turn off inlining to have this covered.

**Comment by jimhester** [comment]
See discussion of inlining at https://gcc.gnu.org/onlinedocs/gcc/Gcov-and-Optimization.html

**Comment by Enchufa2** [comment]
Mmmmh, true, but other functions are not inline. Maybe the compiler is inlining those too? I'll try to deactivate inlining and check what happens.

**Comment by Enchufa2** [comment]
I tried [these flags](https://github.com/Enchufa2/simmer/blob/master/.travis.yml#L6):

```PKG_CXXFLAGS="-O0 -fprofile-arcs -ftest-coverage -Wall -Wno-unused -pedantic"```

[with no luck](https://coveralls.io/builds/5718815). Am I missing something?

**Comment by jimhester** [comment]
Covr already turns off optimization and turns on coverage, you need to set what compiler options it uses using the global option `covr.flags`

```r
options(covr.flags = c(CPPFLAGS = "-O0 -g -coverage -fno-inline", LDFLAGS = "-coverage"))
(cov <- package_coverage(quiet = FALSE))
# for a local interactive report
shine(cov)
```

**Comment by Enchufa2** [comment]
Ok, I see. That solves the coverage problems with inline functions, thank you. But still I see some problems with virtual functions and templated classes. Any clues on this?

**Comment by Enchufa2** [comment]
Sorry to bother you again with this matter, but I'm trying to understand why [this virtual method](https://coveralls.io/builds/7690199/source?filename=src%2Factivity.h#L38) in an abstract class is not covered if there are hundreds of calls to it (for instance, [this](https://coveralls.io/builds/7690199/source?filename=src%2Factivity.h#L137)) from derived classes.

I've prepared an equivalent example: an abstract class with a virtual method which is called by the child class. Here it is:

```c++
#include <iostream>

class Parent {
public:
  virtual ~Parent() {
    std::cout << "I am parent's destructor" << std::endl;
  }
  virtual void method1() {
    std::cout << "I am parent's method 1" << std::endl;
  }
  virtual void method2() = 0;
};

class Child : public Parent {
public:
  ~Child() {
    std::cout << "I am child's destructor" << std::endl;
  }
  void method1() {
    Parent::method1();
    std::cout << "I am child's method 1" << std::endl;
  }
  void method2() {
    std::cout << "I am child's method 2" << std::endl;
  }
};

int main(int argc, char** argv) {
  Parent* obj = new Child();
  obj->method1();
  obj->method2();
  delete obj;
  return 0;
}
```

I run `gcov`:

```bash
g++ -O0 -coverage test.cpp
./a.out
gcov test.cpp
```

and I get that all lines are covered, as expected. Could it be a parsing error in `covr`?

**Comment by jimhester** [comment]
It could be, if you run `package_coverage(clean = F)` you can inspect the `.gcov` files directly and see if they have the expected coverage.

**Comment by Enchufa2** [comment]
I was trying that, but I don't see the `.gcov` files. They are supposed to be found inside the `src` dir, right? I see the `.o` and `.gcda` files there, but the `.gcov` ones are missing.

**Comment by Enchufa2** [comment]
Ok, those lines are marked with `####`, so there is no problem with `covr`. I'll continue investigating. Thanks!
