### ISSUE TITLE
`-O0` needs to be _after_ `-O2`, not before

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#165]
Should be using `CFLAGS += -coverage -O0`, `CXXFLAGS += -coverage -O0` etc.

**Comment by Enchufa2** [comment]
`-O0` appears __before__ `-O2` when I set `covr.flags` with the current `master` version:

````{r}
library(covr)
options(covr.flags = c(CPPFLAGS = "-O0 -g -coverage -fno-inline", LDFLAGS = "-coverage"))
(cov <- package_coverage(quiet = FALSE))

#> g++ -m64 -I/usr/include/R -DNDEBUG  -I/usr/local/include -O0 -g -coverage -fno-inline 
#> -I"/home/***/R/x86_64-redhat-linux-gnu-library/3.2/Rcpp/include" 
#> -I"/home/***/R/x86_64-redhat-linux-gnu-library/3.2/BH/include"  -Wall -Wno-long-long -pedantic 
#> -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions 
#> -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches 
#> -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  
#> -c RcppExports.cpp -o RcppExports.o
```

Etc.

**Comment by jimhester** [comment]
Yes, that is why this is an open issue. This will be fixed once I merge https://github.com/jimhester/covr/tree/simplify_environments?files=1

**Comment by Enchufa2** [comment]
Ok, sorry. I reported this because it appears after `-O2` when I don't set `covr.flags`, so I wasn't sure about the status of this bug. Just in case. :wink:

**Comment by jimhester** [comment]
If you use the current master and set `CFLAGS` and `CXXFLAGS` instead of `CPPFLAGS` it should work as intended.
