### ISSUE TITLE
The Makevars part for vignettes does not exist any more

### ISSUE THREAD

**Issue by maodunzhe** [jimhester/covr#172]
I found that in the explanation of how it works, the Makevars part does not exist in the current branch and the link [R/makevars.R](https://github.com/jimhester/covr/blob/9753e0e257b053059b85be90ef6eb614a5af9bba/R/makevars.R) is pointing to a rather old branch. I think the way to work around this is already updated, could you make the change in the part correspondingly? thanks.

**Comment by jimhester** [comment]
The code was moved to [withr](jimhester/withr), but the principle is the same.

**Comment by maodunzhe** [comment]
The link you provide is not existing and to be clear, you mean the way you leverage the `withr` package in `covr` did the same thing as previous Makevars?

**Comment by jimhester** [comment]
yes
