### ISSUE TITLE
confusion for function replacements_S4

### ISSUE THREAD

**Issue by maodunzhe** [jimhester/covr#173]
I got some confusion for the [R/S4.R](https://github.com/jimhester/covr/blob/master/R/S4.R) here. In `what <- methodsPackageMetaName("T", paste(name, package, sep = ":"))`, the name is got from the the first parameter of Map which is supposed to be a function call(closure) from the `generics@.Data `and the package is a character type got from `generics@package`, I suppose the `paste(name, package, sep = ":")` will generate an error here with the concatenation of string and function call. What's more, could you explain what is the `methodsPackageMetaName` exactly doing, like the first argument 'T' is for what, and how should we leverage this? Thanks!

**Comment by jimhester** [comment]
This function was derived from similar functions in the methods package. If you want to understand how the method package stores and retrieves S4 generics and methods I would suggest you look at the code for the methods package, particularly `utils::methods()` and `methods:::.S4methodsForGeneric()`.

The first argument to `Map()` is `f`, which is given as a named parameter on [R/S4.R#L6](https://github.com/jimhester/covr/blob/master/R/S4.R#L6). The other two arguments are what is being mapped over.

**Comment by maodunzhe** [comment]
Thanks, I will take a look at the methods package then. For the Map() function, I mean here you pass the `generics@.Data` and `generics@package` to the `f()` function you created in the `Map()` . But `generics@.Data` returns a closure type and `generics@package` returns a string type, will the `paste(name, package, sep = ":")` generate an error here with the concatenation of string and function call here?
