### ISSUE TITLE
xml2 has to be installed on travis for export of results to codecov.io

### ISSUE THREAD

**Issue by masalmon** [jimhester/covr#175]
I had to add an installation instruction for xml2 in my travis config file for getting coverage results on codecov.io see https://travis-ci.org/masalmon/geoparser/builds/128557765 Now that I install xml2 on travis it works.

Do you think it is because of the new codecov.io version? Or had I missed something before?

**Comment by jimhester** [comment]
The new version of codecov.io must be returning an HTML or XML response rather than a JSON response, so it is hitting https://github.com/hadley/httr/blob/f2c3c4d48ee5f32a77449fff578ebf05f5dd89a2/R/content-parse.r#L91

I will see if I can reproduce this and force a JSON response always.
