### ISSUE TITLE
package_coverage fails on package with Rcpp/Rstan

### ISSUE THREAD

**Issue by dmenne** [jimhester/covr#178]
My packages that include Stan-based Rcpp files (similar to rstanarm) run into an error with package_coverage(). 

```
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: running command '"C:/R/bin/x64/R" CMD INSTALL --example --install-tests --with-keep.source --no-multiarch -l "C:\Users\Dieter\AppData\Local\Temp\RtmpcFebWN\R_LIBS23ec6c465cd4" "C:/Users/Dieter/Documents/RPackages/teststan"' had status 1 
2: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘C:/Users/Dieter/Documents/RPackages/teststan’ had non-zero exit status
3: In file(con, "r") :
  cannot open file 'C:/Users/Dieter/AppData/Local/Temp/RtmpcFebWN/R_LIBS23ec6c465cd4/teststan/R/teststan': No such file or directory
```
For a minimal example using one test, see https://github.com/dmenne/teststan . The example above ran locally on Windows 10; coverage for non-Rcpp packages is Ok. 

A similar error on Travis: https://travis-ci.org/dmenne/teststan

```
$ Rscript -e 'covr::coveralls()'
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> -> package_coverage -> add_hooks -> readLines -> file
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘/home/travis/build/dmenne/teststan’ had non-zero exit status
2: In file(con, "r") :
  cannot open file '/tmp/Rtmp4NymV2/R_LIBS2553189d617/teststan/R/teststan': No such file or directory

Execution halted
```

**Comment by jimhester** [comment]
The stan generated code is not available until the package has been built. If you build the package, extract the code and then run covr on the extracted package coverage is generated appropriately.

Running R CMD build prior to installation was something I was trying to avoid, but perhaps we must do so.

**Comment by dmenne** [comment]
Sorry that I forgot to mention that it runs without problems with a pre-built package! I just thought that I had forgotten something to make it work without pre-building. No problem for local work, but I admit that I am not good enough in travis-ci yaml to get it to work there.

**Comment by jimhester** [comment]
R-travis builds a tarball before running R CMD check (see [r.rb#L192-197](https://github.com/travis-ci/travis-build/blob/f4d531479b01d8526b57f2e59b859e5713920605/lib/travis/build/script/r.rb#L192-L197)), so you can just extract this before running coverage. Something like the following should work.

```yaml
after_success:
  - tar -C .. xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
```

**Comment by dmenne** [comment]
Little typo, but otherwise great! Thanks.

     - tar -C .. --xf $PKG_TARBALL

https://travis-ci.org/dmenne/teststan/builds/130593936

**Comment by amarder** [comment]
Hi Dieter,

I think your comment above has a minor typo (an extra dash before the xf). Here's the correct line copied from your [.travis.yml](https://github.com/dmenne/teststan/blob/master/.travis.yml) file:

    - tar -C .. -xf $PKG_TARBALL

Thanks for figuring this out, Dieter and Jim!

Andrew
