### ISSUE TITLE
package_coverage always has length zero

### ISSUE THREAD

**Issue by richierocks** [jimhester/covr#179]
Regardless of which package I test, I get no test coverage score.

For example, I just cloned `lintr` from github, then (in its directory) ran:

``` r
coverage <- covr::package_coverage(".")
length(coverage)
## [1] 0
> covr::percent_coverage(coverage)
## [1] NaN
```

I'm using today's version of `covr`, (2.0.1.9000), tested with several recent versions of R, under Windows 10.

**Comment by jimhester** [comment]
Do you get any error message with `quiet = FALSE`? Have you already installed all the dependencies needed to test lintr previously? You can use `devtools::install_deps(dependencies = TRUE)` to install them if not.

I verified the current version works fine OS X and windows 10 in a VM on my machine.

**Comment by richierocks** [comment]
There's no obvious error with `quiet = FALSE`.  The output I see is:
```
coverage <- covr::package_coverage(".", quiet = FALSE)
* installing *source* package 'lintr' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'lintr'
    with_defaults                           example
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (lintr)
```
All the dependencies are installed.  They are in the library given by `Sys.getenv("R_LIBS")`, rather than R's default; I don't know if that makes a difference?

Here are the files that were created during the process:
[R_LIBS235428ef17e5.zip](https://github.com/jimhester/covr/files/267471/R_LIBS235428ef17e5.zip)

I've tried a few different packages, including those with no dependencies other than base-R packages.  I've also tried running on a different (Win 7) machine, and tried running directly in RGui.  In all cases I get the same `NaN` result.

**Comment by richierocks** [comment]
`type = "examples"` works for me, but `type = "tests"` and `type = "vignettes"` both fail.

**Comment by jimhester** [comment]
I don't see anything wrong in your output other than the fact that no trace files are being written to the R_LIBS* directory, so either the finalizer is not being called or it is not able to write to the directory. Can you ensure you have write permissions to `tempdir()`.

The only other thing I saw was the following warning in lintr-tests/testthat.Rout
```r
Warning message:
package 'testthat' was built under R version 3.4.0
```

It is generally bad practice to share a library between major versions of R, you may want to try with a fresh library.

**Comment by kforner** [comment]
I think I've been hit by the same problem. Your **R_LIBS** var overrides the internal covr hooked package, so that it is your original package which is loaded by the coverage, not the hooked/instrumented one.
