### ISSUE TITLE
Exclude lines from coverage

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#18]
It is probably beneficial for a package developer to exclude lines from their coverage.  I could see two interfaces for this

1. as a parameter to the given coverage function
  - named vector with filenames `c(src/test.R = c(2, 3, 5, 6, 10:20))`
2. as an annotation within the source file
  - `# no_covr`
  - `# no_covr_start`
  - `# no_covr_end`

They both have positive and negatives in my mind, perhaps the best solution is to use both...

**Comment by jackwasey** [comment]
This would interest me greatly. Could it be done more simply by a filter in/out of source files as an argument to `coveralls`? Another approach could be filtering in/our function names. This would give flexibility to change the coverage tests without digging through source code. Thanks for a great tool.

**Comment by jimhester** [comment]
Filtering by function names is a good idea, but would be tricky to implement since we don't keep the enclosing function of each call.

I added support for excluding with a6f65315c78c2e9675e2564a02653f144c847566 using both the approaches above, so you can exclude with a list of files and lines with `exclusion=list("R/file.R" = c(10:20), "R/file2.R" = 1)` or by adding `# EXCLUDE COVERAGE`, or paired `# EXCLUDE COVERAGE START`, `# EXCLUDE COVERAGE END` to the source.  Those patterns can also be set by the user if they need to change them.

Maybe I should also allow excluding a file completely by passing just the filename, but for now I will leave it as-is.

**Comment by jackwasey** [comment]
fantastic

**Comment by jackwasey** [comment]
Hmm, I have the exclusion ranges working. I initially thought that # EXCLUDE COVERAGE would exclude the whole file, but it seem that it just excludes one line. However, I don't seem to be able to exclude specific files with any of the following in my .travis.yml

`Rscript -e 'library(covr); coveralls(exclusion=list("./R/RcppExports.R" = c(0,5000), "./src/RcppExports.cpp" = c(0,5000)))'`
`Rscript -e 'library(covr); coveralls(exclusion=list("./R/RcppExports.R" = 1, "./src/RcppExports.cpp" = 1))'`
`Rscript -e 'library(covr); coveralls(exclusion=list("R/RcppExports.R" = c(0,5000), "src/RcppExports.cpp" = c(0,5000)))'`
Coverage reported here:
https://coveralls.io/builds/1791032
.travis.yml at
https://github.com/jackwasey/icd9/blob/rcpp-optim/.travis.yml
