### ISSUE TITLE
Coverage different on travis compared with locally.

### ISSUE THREAD

**Issue by jonkeane** [jimhester/covr#180]
I’ve been using covr (via travis) for a little while now, and I noticed something strange which I haven’t been able to diagnose yet. It seems that the coverage totals I’m getting on travis (both on linux and OS X) are much lower than when I run package_coverage() on my local machine. 

My tests are written with testthat, and they pass on travis, but it seems that covr is not able to track that some lines are covered. Could you give me any pointers why this might be the case? I’m sure I’m missing something very simple. Thanks.

Here are some examples:
on my devel branch, on travis (for example https://travis-ci.org/jonkeane/mocapGrip/jobs/129502952): 
$ Rscript -e 'covr::package_coverage()'
mocapGrip Coverage: 10.16%
R/CoefficientPlot.R: 0.00%
R/elanUtils.R: 0.00%
R/extractMocapDataFromAnnotations.R: 0.00%
R/ggCaterpillar.R: 0.00%
R/gripClipping.R: 0.00%
R/modelStructure.R: 0.00%
R/obsisReadingFuncs.R: 0.00%
R/parseExtractedAnnotations.R: 0.00%
R/predictions.R: 0.00%
R/reportWriter.R: 36.36%
R/analyze.R: 98.11%

But on the same commit, on my local machine:
> covr::package_coverage("./")
mocapGrip Coverage: 39.21%
R/CoefficientPlot.R: 0.00%
R/elanUtils.R: 0.00%
R/extractMocapDataFromAnnotations.R: 0.00%
R/ggCaterpillar.R: 0.00%
R/predictions.R: 0.00%
R/obsisReadingFuncs.R: 4.05%
R/gripClipping.R: 18.38%
R/parseExtractedAnnotations.R: 66.67%
R/modelStructure.R: 90.00%
R/reportWriter.R: 90.91%
R/analyze.R: 98.11%

**Comment by jimhester** [comment]
Try running with just `R` rather than `Rscript`. Rscript does not load the methods package and this sometimes causes issues.

**Comment by jonkeane** [comment]
Changing to `echo 'covr::codecov()' | R --vanilla` worked perfectly. Thanks for the info.
