### ISSUE TITLE
Switch statement in setMethod() not being picked up?

### ISSUE THREAD

**Issue by PeteHaitch** [jimhester/covr#182]
Hi Jim,
The [tests](https://github.com/PeteHaitch/DSArray/blob/master/tests/testthat/test-Summary.R) for my [`Summary,DSArray-method`](https://github.com/PeteHaitch/DSArray/blob/master/R/Summary.R) are not being picked up by **covr**, at least that's what `covr::shine(covr::package_coverage())` is telling me. The method uses a `switch()` statement to handle the multiple member generic functions that are part of the `Summary` S4 group generic. I realise this might not be a common use case, but can you give me any pointers as to why **covr** isn't picking up these lines and whether there's anything I can do about or if it's just a nasty corner case.

My repo is https://github.com/PeteHaitch/DSArray

Thanks,
Pete

**Comment by jimhester** [comment]
I recently looking into switch statements and believe this should now be fixed.
