### ISSUE TITLE
package_coverage() works when run in R but fails when run in Rscript

### ISSUE THREAD

**Issue by ThierryO** [jimhester/covr#183]
Some output when run in R.

R/status.R: 54.37%
R/get_analysis_version.R: 77.42%
R/get_model_parameter.R: 78.55%
R/get_result.R: 82.16%
R/n2k_glmer_poisson.R: 96.03%

Same output from Rscript

R/parent_status.R: 0.00%
R/get_analysis_version.R: 0.00%
R/get_model_parameter.R: 0.00%
R/get_result.R: 0.00%
R/n2k_glmer_poisson.R: 0.00%

To code below generates a reproducible example based on a docker image.

    docker run --net=host -it --rm inbonatura2000/n2khelper:dev-0.2-full /bin/bash

    git clone https://github.com/thierryo/n2kanalysis
    cd n2kanalysis
    git checkout lincomd_list

    R
    covr::package_coverage(quiet = FALSE)
    q(save = "no")

    Rscript -e 'covr::package_coverage(quiet = FALSE)'

**Comment by jimhester** [comment]
Rscript does not load the methods package by default. You can specify it
explicitly with the `--default-packages` argument.

**Comment by ThierryO** [comment]
Thank you for the fast response. I've tried the variants below. Unfortunately they don't solve the problem. Is there something that I'm missing?

```
Rscript -e 'library(methods);covr::package_coverage(quiet = FALSE)'
Rscript -e 'library(methods);library(covr);package_coverage(quiet = FALSE)'
Rscript --default-packages='methods' -e 'covr::package_coverage(quiet = FALSE)'
Rscript --default-packages='methods' -e 'library(covr);package_coverage(quiet = FALSE)'
```

**Comment by jimhester** [comment]
You need to specify all the default packages you need, not just methods, `R` defaults to `datasets,utils,grDevices,graphics,stats,methods` so the following gives you proper coverage
```
Rscript --default-packages='datasets,utils,grDevices,graphics,stats,methods' -e 'covr::package_coverage()'
```
However you can correct results in this case with just `utils,stats,methods`.

Alternatively just use R directly
```bash
R -q -e 'covr::package_coverage()'
```
