### ISSUE TITLE
package_coverage() works locally but coveralls() says ~0% on travis

### ISSUE THREAD

**Issue by cdeterman** [jimhester/covr#184]
I am able to run `package_coverage()` locally and I see many of my files have coverage.  However, on Travis CI the `coveralls()` result is showing ~0% coverage.  Any thoughts?

You can see the most recent build [here](https://travis-ci.org/cdeterman/bigmemory).

Relevant section from `.travis.yml`

    after_success:
      - Rscript --default-packages='utils,stats,methods' -e 'library(covr);coveralls()'

**Comment by jimhester** [comment]
You may want to try with 'datasets,utils,grDevices,graphics,stats,methods', or just use `R -e` directly.

**Comment by cdeterman** [comment]
I added the additional packages with no luck.  I will try the `-e` method and let you know what happens.  You can see the coveralls page [here](https://coveralls.io/github/cdeterman/bigmemory) and the [yml file](https://github.com/cdeterman/bigmemory/blob/master/.travis.yml).

**Comment by cdeterman** [comment]
Still no luck with the simple `-e` call either.

**Comment by johndharrison** [comment]
Hi Charles,

Your tests are named test_* in the testthat directory. If you rename them to test-* the TRAVIS coverage should work.

**Comment by cdeterman** [comment]
@johndharrison I will give the renaming a go however it seems strange to me that it wouldn't work here when I have test files prefixed with test_* in another [one of my repositories](https://github.com/cdeterman/gpuR) where it works without a problem.

**Comment by cdeterman** [comment]
@johndharrison The renaming failed to fix the problem.  Any other thoughts?

**Comment by johndharrison** [comment]
@cdeterman this fixed a similar issue for me however it was codecov rather than coveralls.

**Comment by cdeterman** [comment]
I'm really quite confused because all the tests pass without a problem within the [travis environment](https://travis-ci.org/cdeterman/bigmemory/builds/159880897) as well.

**Comment by cdeterman** [comment]
@johndharrison it also appears to be a problem with [codecov too ](https://codecov.io/gh/cdeterman/bigmemory/tree/42faa982a55f8cf082e7c654879441657332323a) so I must be missing something here.

**Comment by privefl** [comment]
Is it normal that Codecov does not track any of the test files?

![](https://raw.githubusercontent.com/privefl/bigmemory/master/untracked.png)

**Comment by jimhester** [comment]
@privefl, yes it is normal, the test files are what is being run to generate the coverage and are not part of the package namespace.

**Comment by jimhester** [comment]
@cdeterman Running `cov <- covr::package_coverage()` is seg faulting on my machine, I imagine you have a bug in your program that is happening when compiling with `-O0`. There are a number of warnings about uninitialized variables used for indexing. Try running with `covr::package_coverage(quiet = F, clean = F)` and see if you can track down the issue.

**Comment by cdeterman** [comment]
@jimhester I have run in locally with `covr::package_coverage(quiet = F, clean = F)` and it ran without a problem.  Seeing that the cleanup wasn't important I ran it on Travis with just `covr::package_coverage(quiet = F)`.  Again, no obvious issues (warnings or otherwise) but still very low coverage.  You can see the most recent build [here](https://travis-ci.org/cdeterman/bigmemory/builds/160432143).

**Comment by cdeterman** [comment]
@jimhester I managed to reproduce the problem on another virtual machine (Ubuntu 14.04) but again the output is the same as on Travis.  The tests all pass and the `package_coverage` call has no apparent errors.  Thoughts?

**Comment by cdeterman** [comment]
@jimhester okay, sorry for so many replies but I have finally got the crash you mentioned.  I needed to set `CXXFLAGS=O0` in my `.R/Makevars` file.  I will poke around and see what I can figure out now.

**Comment by cdeterman** [comment]
@jimhester I have solved the problem after adding all the `CXXFLAGS` to output the uninitialized warnings allowing me to sort out where the segfault was happening.  Thanks very much for your assistance.
