### ISSUE TITLE
useless call ?

### ISSUE THREAD

**Issue by kforner** [jimhester/covr#186]
Hi,
Naively, this call at https://github.com/jimhester/covr/blob/master/R/covr.R#L224 
seems useless when `code` is empty:
```run_commands(pkg, tmp_lib, code)   ```
but maybe I'm missing something.

best,

**Comment by jimhester** [comment]
Running it unconditionally is a useful way to ensure we instrument the code and produce 0% output even if there are no tests in the package.

**Comment by kforner** [comment]
ok I get it. Maybe this could be commented then, since it it is not obvious you are using a side-effect. 

Or better, handling this in a  read_r_traces() function would IMHO be faster and simpler to understand ?
something like:
```



read_r_traces <- function(dir) {
  coverage <- list()
  trace_files <- list.files(path = dir, pattern = "^covr_trace_[^/]+$", full.names = TRUE)
  if (length(trace_files) > 0) {
   coverage <- merge_coverage(lapply(trace_files, function(x) as.list(readRDS(x))))
  }
  new_coverage(coverage)
}

new_coverage <- function(x, ...) structure(x, class = 'coverage', ...)

 ```
then in package_coverage(), around lines 231:
```
coverage <- new_coverage(c(read_r_traces(tmp_lib), run_gcov(pkg$path, quiet = quiet)),
          package = pkg, relative = relative_path)

```

**Comment by jimhester** [comment]
You lose what lines are being traced by doing that, you need to run an R process to instrument the package at some point.

**Comment by kforner** [comment]
that's what I do not understand. cf my next issue describing my exact problem. thanks.

**Comment by kforner** [comment]
> you need to run an R process to instrument the package at some point.

but tools::testInstalledPackage() actually runs a R process right ? 
and the R process run by run_commands() does run the tests, so it instruments the code for nothing ?

**Comment by jimhester** [comment]
`testInstalledPackage()` only runs an R process if a `tests` directory exists and there are `*.R` files in it.

**Comment by kforner** [comment]
>You lose what lines are being traced by doing that, you need to run an R process to instrument the package at some point.

ok, You mean if there are no tests, you're still interested by the coverage, even if it is 0% covered. For this you need at least a trace.  makes sense, thank you.

**Comment by jimhester** [comment]
Yeah exactly, sorry for the confusion!
