### ISSUE TITLE
run_commands() var names

### ISSUE THREAD

**Issue by kforner** [jimhester/covr#187]
Just some comments as I try to understand the code. 
Feel free to ignore them, and tell me if you prefer that I keep them for me in the future.
 (sorry I have been formatted by Mr H.)
Anyway:
 - $pkg-commands.Rout is actually the input file for R CMD BATCH, so the name is misleading
  -$pkg-commands.Rout.fail is the output of R CMD BATCH, even if it succeeds, so probably misnamed too.

**Comment by jimhester** [comment]
That code is based on the code in `tools::testInstalledPackages()` and uses the same naming conventions. The part missing was renaming the file if the command succeeds, which I just added in de0aadb

**Comment by kforner** [comment]
ok, thanks
