### ISSUE TITLE
problem using `capture.output` in tests

### ISSUE THREAD

**Issue by kingaa** [jimhester/covr#192]
Thanks for your great package.  It's been tremendously helpful to me!

In package tests, a call to `capture.output` seems to interfere badly with `package_coverage`.  This may be unavoidable, but should perhaps be documented?

Apologies if I've missed something!

**Comment by jimhester** [comment]
Could you provide an simple reproducible example of the problem?

**Comment by kingaa** [comment]
Thought it would be straightforward.  As it happens, it isn't.  Will close this issue and re-open if it arises again.
