### ISSUE TITLE
If tools::testInstalledPackage() returns -1 print .fail file

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#194]

**Comment by realAkhmed** [comment]
@jimhester was subbed to this issue. Was that general idea abandoned or was it implemented ?

**Comment by jimhester** [comment]
It was implemented (https://github.com/jimhester/covr/commit/81b4a4a986c29f562e198285fa321412b61ef97a), I just neglected to close the issue, or more likely forgot there was an open issue for this.

**Comment by realAkhmed** [comment]
Excellent. thanks!
