### ISSUE TITLE
Coverage for "dynamically" Generated Functions

### ISSUE THREAD

**Issue by brodieG** [jimhester/covr#199]
This one is pretty low priority since it is a fairly esoteric corner case:
```
make_fun_1 <- function() {
  function(x) {
    1 + 1
    2 + 2
    cat("fun1\n")
  }
}
fun1 <- make_fun_1()
```
With a test file that calls `fun1()`  does not show coverage of `1 + 1`, etc. even though that code is run.  I suspect this is different to issue #113 since `fun1` should be detected as a function in the namespace.  Likely the problem is that the function definition itself doesn't exist in a concrete manner that can be systematically defined in the source code.

I'm guessing the most likely outcome for this issue is "wontfix", but posting here just in case there is actually a simple resolution.

In case you're wondering about why anyone would ever want to do this: I happen to have a family of functions that are all almost the same and share the same formal arguments, so rather than defining each function separately I use a constructing function to avoid having to re-state a lengthy argument list every time (and risk messing it up for one of the functions when tweaking, etc.).

**Comment by jimhester** [comment]
I think there must be more going on here, this is basically the same thing as with reference classes, which are covered as you would expect. Also your example looks to me like it is working correctly with the 3rd, 4th and 5th lines being traced and covered.

``` r
make_fun_1 <- function() {
  function(x) {
    1 + 1
    2 + 2
    cat("fun1\n")
  }
}
fun1 <- make_fun_1()

as.data.frame(function_coverage(fun1, fun1(1)))
#> fun1
#>   filename functions first_line first_byte last_line last_byte
#> 1   <text>      fun1          3          5         3         9
#> 2   <text>      fun1          4          5         4         9
#> 3   <text>      fun1          5          5         5        17
#>   first_column last_column first_parsed last_parsed value
#> 1            5           9            3           3     1
#> 2            5           9            4           4     1
#> 3            5          17            5           5     1
```

**Comment by brodieG** [comment]
Okay, I'll look at this more this weekend and try to figure out why coverage shows up with `function_coverage` but not in my use case in the package.

**Comment by brodieG** [comment]
Some more details with a [test package](https://github.com/brodieG/covrtest):

```
library(devtools)
install_github("brodieg/covrtest")
library(covrtest)
as.data.frame(function_coverage(fun1, fun1(1)))
# fun1
#  [1] filename     functions    first_line   first_byte   last_line   
#  [6] last_byte    first_column last_column  first_parsed last_parsed 
# [11] value       
# <0 rows> (or 0-length row.names)
fun1
# function (x) 
# {
#     1 + 1
#     2 + 2
#     cat("fun1\n")
# }
# <environment: 0x7fd0048cb0a8>
parent.env(environment(fun1))
# <environment: namespace:covrtest>
```

I'm not sure how to interpret the fact that I get zero coverage when basically all I'm doing is what you did within a package instead of in the workspace.  I get the same result you do if I just copy paste in the workspace (fwiw, I'm on latest cran version 2.1.0).

I'm guessing the problem is related to `covr:::replace` somehow being able to properly replace the function in this nested case only when the function grand-parent environment is `.GlobalEnv`.  No idea why that would be the case.

**Comment by brodieG** [comment]
So the difference between the package version and the command line version is that the former doesn't automatically have source refs attached to the function.  If I install with `keep_source` then this starts working.  Unfortunately `trace_calls` is a bit too complicated for me to be able to easily tell why normal functions in packages without `keep_source` work, but not this "dynamically" generated variety.

Also, while I can get `function_coverage` to work if I build the package with `keep_source`, `package_coverage` does not, at least as far as I can tell.  From poking around it looks like `package_coverage` uses `--with-keep.source` so it should work.

Anyhow, this is all fairly unfamiliar territory for me so I'll wait see if you have any insights here before I dig further.  Again, pretty low priority so "won't fix" is definitely a reasonable outcome.

**Comment by brodieG** [comment]
Ok, I bet the issue is coming from [trace_environments](https://github.com/jimhester/covr/blob/master/R/covr.R#L19), where we explicitly supply `env` to `replacement`:

```
trace_environment <- function(env) {
  clear_counters()

  the$replacements <- compact(c(
      replacements_S4(env),
      replacements_RC(env),
      replacements_R6(env),
      lapply(ls(env, all.names = TRUE), replacement, env = env)))

  lapply(the$replacements, replace)
}
```

And that environment will be the wrong environment (the namespace), whereas when we use `function_coverage` that one actually passes the function environment as the replacement environment.  I don't have time to test now, but if you think this is the problem I can look into fixing.

**Comment by jimhester** [comment]
It does seem to be working properly if you call `trace_environment()` manually.

``` r
covr:::trace_environment(asNamespace("covrtest"))
#> [[1]]
#> NULL
#> 
#> [[2]]
#> NULL
#> 
#> [[3]]
#> NULL
#> 
#> [[4]]
#> NULL
#> 
#> [[5]]
#> NULL
#> 
#> [[6]]
#> NULL
#> 
#> [[7]]
#> NULL
#> 
#> [[8]]
#> NULL
#> 
#> [[9]]
#> NULL
#> 
#> [[10]]
#> NULL
#> 
#> [[11]]
#> NULL
covrtest:::fun1("hello")
#> fun1
covrtest:::fun2(1L)
#> fun2
covrtest:::fun2(1)
#> fun3
covrtest:::fun5(1)
#> fun4
as.list(covr:::.counters)
#> $`test.R:18:5:18:9:5:9:20:20`
#> $`test.R:18:5:18:9:5:9:20:20`$value
#> [1] 1
#> 
#> $`test.R:18:5:18:9:5:9:20:20`$srcref
#> 1 + 1
#> 
#> $`test.R:18:5:18:9:5:9:20:20`$functions
#> [1] "make_fun_3"
#> 
#> 
#> $`test.R:10:5:10:9:5:9:12:12`
#> $`test.R:10:5:10:9:5:9:12:12`$value
#> [1] 1
#> 
#> $`test.R:10:5:10:9:5:9:12:12`$srcref
#> 2 + 2
#> 
#> $`test.R:10:5:10:9:5:9:12:12`$functions
#> [1] "make_fun_2"
#> 
#> 
#> $`test.R:4:5:4:9:5:9:6:6`
#> $`test.R:4:5:4:9:5:9:6:6`$value
#> [1] 1
#> 
#> $`test.R:4:5:4:9:5:9:6:6`$srcref
#> 1 + 1
#> 
#> $`test.R:4:5:4:9:5:9:6:6`$functions
#> [1] "make_fun_1"
#> 
#> 
#> $`test.R:12:5:12:17:5:17:14:14`
#> $`test.R:12:5:12:17:5:17:14:14`$value
#> [1] 1
#> 
#> $`test.R:12:5:12:17:5:17:14:14`$srcref
#> cat("fun2\n")
#> 
#> $`test.R:12:5:12:17:5:17:14:14`$functions
#> [1] "make_fun_2"
#> 
#> 
#> $`test.R:3:5:3:9:5:9:5:5`
#> $`test.R:3:5:3:9:5:9:5:5`$value
#> [1] 1
#> 
#> $`test.R:3:5:3:9:5:9:5:5`$srcref
#> 2 + 2
#> 
#> $`test.R:3:5:3:9:5:9:5:5`$functions
#> [1] "make_fun_1"
#> 
#> 
#> $`test.R:5:5:5:17:5:17:7:7`
#> $`test.R:5:5:5:17:5:17:7:7`$value
#> [1] 1
#> 
#> $`test.R:5:5:5:17:5:17:7:7`$srcref
#> cat("fun1\n")
#> 
#> $`test.R:5:5:5:17:5:17:7:7`$functions
#> [1] "make_fun_1"
#> 
#> 
#> $`test.R:34:3:34:7:3:7:36:36`
#> $`test.R:34:3:34:7:3:7:36:36`$value
#> [1] 1
#> 
#> $`test.R:34:3:34:7:3:7:36:36`$srcref
#> 2 + 2
#> 
#> $`test.R:34:3:34:7:3:7:36:36`$functions
#> [1] "fun5"
#> 
#> 
#> $`test.R:9:3:13:3:3:3:11:15`
#> $`test.R:9:3:13:3:3:3:11:15`$value
#> [1] 0
#> 
#> $`test.R:9:3:13:3:3:3:11:15`$srcref
#> function(x) {
#>     2 + 2
#>     1 + 1
#>     cat("fun2\n")
#>   }
#> 
#> $`test.R:9:3:13:3:3:3:11:15`$functions
#> [1] "make_fun_2"
#> 
#> 
#> $`test.R:11:5:11:9:5:9:13:13`
#> $`test.R:11:5:11:9:5:9:13:13`$value
#> [1] 1
#> 
#> $`test.R:11:5:11:9:5:9:13:13`$srcref
#> 1 + 1
#> 
#> $`test.R:11:5:11:9:5:9:13:13`$functions
#> [1] "make_fun_2"
#> 
#> 
#> $`test.R:41:20:41:54:20:54:43:43`
#> $`test.R:41:20:41:54:20:54:43:43`$value
#> [1] 0
#> 
#> $`test.R:41:20:41:54:20:54:43:43`$srcref
#> function(x) StandardGeneric("fun2")
#> 
#> $`test.R:41:20:41:54:20:54:43:43`$functions
#> [1] "ANY"
#> 
#> 
#> $`test.R:35:3:35:15:3:15:37:37`
#> $`test.R:35:3:35:15:3:15:37:37`$value
#> [1] 1
#> 
#> $`test.R:35:3:35:15:3:15:37:37`$srcref
#> cat("fun4\n")
#> 
#> $`test.R:35:3:35:15:3:15:37:37`$functions
#> [1] "fun5"
#> 
#> 
#> $`test.R:19:5:19:17:5:17:21:21`
#> $`test.R:19:5:19:17:5:17:21:21`$value
#> [1] 1
#> 
#> $`test.R:19:5:19:17:5:17:21:21`$srcref
#> cat("fun3\n")
#> 
#> $`test.R:19:5:19:17:5:17:21:21`$functions
#> [1] "make_fun_3"
#> 
#> 
#> $`test.R:33:3:33:7:3:7:35:35`
#> $`test.R:33:3:33:7:3:7:35:35`$value
#> [1] 1
#> 
#> $`test.R:33:3:33:7:3:7:35:35`$srcref
#> 1 + 1
#> 
#> $`test.R:33:3:33:7:3:7:35:35`$functions
#> [1] "fun5"
#> 
#> 
#> $`test.R:16:3:20:3:3:3:18:22`
#> $`test.R:16:3:20:3:3:3:18:22`$value
#> [1] 0
#> 
#> $`test.R:16:3:20:3:3:3:18:22`$srcref
#> function(x) {
#>     3 + 3
#>     1 + 1
#>     cat("fun3\n")
#>   }
#> 
#> $`test.R:16:3:20:3:3:3:18:22`$functions
#> [1] "make_fun_3"
#> 
#> 
#> $`test.R:2:3:6:3:3:3:4:8`
#> $`test.R:2:3:6:3:3:3:4:8`$value
#> [1] 0
#> 
#> $`test.R:2:3:6:3:3:3:4:8`$srcref
#> function(x) {
#>     2 + 2
#>     1 + 1
#>     cat("fun1\n")
#>   }
#> 
#> $`test.R:2:3:6:3:3:3:4:8`$functions
#> [1] "make_fun_1"
#> 
#> 
#> $`test.R:17:5:17:9:5:9:19:19`
#> $`test.R:17:5:17:9:5:9:19:19`$value
#> [1] 1
#> 
#> $`test.R:17:5:17:9:5:9:19:19`$srcref
#> 3 + 3
#> 
#> $`test.R:17:5:17:9:5:9:19:19`$functions
#> [1] "make_fun_3"
covr:::reset_traces()
#> [[1]]
#> NULL
#> 
#> [[2]]
#> NULL
#> 
#> [[3]]
#> NULL
#> 
#> [[4]]
#> NULL
#> 
#> [[5]]
#> NULL
#> 
#> [[6]]
#> NULL
#> 
#> [[7]]
#> NULL
#> 
#> [[8]]
#> NULL
#> 
#> [[9]]
#> NULL
#> 
#> [[10]]
#> NULL
#> 
#> [[11]]
#> NULL
```

I think it may be an issue based on when functions are defined during package installation / loading, will continue to look into it.

**Comment by jimhester** [comment]
Ah I have figured it out, the way `per_line()` works is it always takes the lowest value of coverage for any given line. This is so something like the following is covered, as otherwise all lines will have 1 coverage (due to the entire if statement having 1 coverage).

```r
if (FALSE) {
  1
} else {
  2
}
```
For the examples you gave while the inner parts of the closure definitions are covered, the entire thing is not because the make_fun_x functions are not called _during_ the tests.

I am not really sure how we can handle this case while preserving the behavior for conditionals, in some sense covr is working as designed here.

**Comment by brodieG** [comment]
Thanks for looking into this.  I think a possible solution here is to compute byte coverage, since we have all the requisite information.  I put up a [strawman implementation](https://github.com/jimhester/covr/compare/master...brodieG:bytecov?expand=1) in my fork.  It requires a bit of work to make sure it works generally, but it appears works in the simple corner cases (in particular, look at `fun3`):

![screen shot 2016-07-05 at 10 13 27 pm](https://cloud.githubusercontent.com/assets/6105908/16605535/c2b09e7a-42fd-11e6-860e-2bbc34e5417f.png)

You'll need to re-download `covrtest` as I made some small changes to it.

The implementation is slightly slower than the existing one (this is with a reasonably large package):
```
> microbenchmark(times=10, covr:::per_line(x), covr:::per_line_old(x))
Unit: milliseconds
                   expr      min       lq     mean   median       uq      max
     covr:::per_line(x) 425.0260 437.4059 444.1664 440.7401 453.0512 463.5039
 covr:::per_line_old(x) 359.5218 359.7610 376.8426 368.8949 377.0267 430.1342
```
but the difference is small compared to the overall evaluation time as it doesn't seem like `per_line` is the bottleneck.

The bigger issue here would be making sure this works in all the cases that the existing `per_line` does, which is definitely not the case currently.  That could take a bit of testing, though getting it to this point didn't take too much time so that's somewhat encouraging.

If you are interested in this feature I can look into it further, though it may be a few weeks before I get around to it.

**Comment by jimhester** [comment]
I would definitely like to fix this, I opened https://github.com/jimhester/covr/pull/203 so we can discuss further there.
