### ISSUE TITLE
is on.exit(clear_counters()) needed in package_coverage() ?

### ISSUE THREAD

**Issue by kforner** [jimhester/covr#200]
About this line:
cf https://github.com/jimhester/covr/blob/master/R/covr.R#L174

From what I understood, the package code is traced in another process, so the counters of the current namespace in the current process should not be modified, hence my question...

The reason I'm asking is in the case of recursive package_coverage() calls, where some traced code (say of package A), contains a call to package_coverage() to compute the coverage of yet another package (say B). At the end of the package_coverage call executed by the R code in A, the counters will be reset (by the on.exit) so that further code will not only be improperly traced (previous tracing is deleted), but will lead to incomplete trace files.

**Comment by jimhester** [comment]
I think you are correct that this is an unnecessary step and will break the recursive call you mention. Happy to merge a PR that removes it if you want to submit one.

**Comment by kforner** [comment]
done, cf PR https://github.com/jimhester/covr/pull/202

**Comment by jimhester** [comment]
Closed by 7fc88bea
