### ISSUE TITLE
covr doesn't identify an example as code coverage

### ISSUE THREAD

**Issue by gvegayon** [jimhester/covr#205]
While I have examples and I have `testthat` to run them, covr won't report coverage in a couple of S3 methods for concatenating objects, in particular: [c.diffnet](https://codecov.io/gh/USCCANA/netdiffuseR/src/21b7499146fbf7fa0008532fc958480d930c0567/R/diffnet-c.R#L50) and [c.diffnet_struct_test](https://codecov.io/gh/USCCANA/netdiffuseR/src/21b7499146fbf7fa0008532fc958480d930c0567/R/struct_test.R#L159)

This further happens with other functions, e.g.: [adopt_changes](https://codecov.io/gh/USCCANA/netdiffuseR/src/21b7499146fbf7fa0008532fc958480d930c0567/R/select_egoalter.R#L57) and [survey_to_diffnet](https://codecov.io/gh/USCCANA/netdiffuseR/src/21b7499146fbf7fa0008532fc958480d930c0567/R/survey_to_diffnet.R#L138)

These results I get both on codecov.io and on my machine

Am I getting something wrong here?

Thanks

```r
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=C               LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] netdiffuseR_1.16.6 covr_2.1.0        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5     lattice_0.20-33 digest_0.6.9    crayon_1.3.2    withr_1.0.2     MASS_7.3-45    
 [7] grid_3.3.1      magrittr_1.5    lazyeval_0.2.0  SparseM_1.7     rex_1.1.1       Matrix_1.2-6   
[13] sna_2.3-2       boot_1.3-18     tools_3.3.1     igraph_1.0.1    memoise_1.0.0 
```

**Comment by gvegayon** [comment]
Hey @jimhester, I was wondering if you have gave this a thought. I'm not sure if this is an issue of covr or of testthat. Thanks

**Comment by jimhester** [comment]
Can you give a more explicit example, where are the tests that are running these functions?

**Comment by gvegayon** [comment]
Sure:

Here is an example of code not identified as covered: https://codecov.io/gh/USCCANA/netdiffuseR/src/48e364cd8d7f7d43be324af56dfb462c8f6c1d91/R/plot_diffnet2.R#L8...36

Here is the manual of that function:
https://github.com/USCCANA/netdiffuseR/blob/48e364cd8d7f7d43be324af56dfb462c8f6c1d91/man/round_to_seq.Rd#L23-L27

Here is the part of the testthat folder that runs the examples (so it does include the function `round_to_seq`):
 https://github.com/USCCANA/netdiffuseR/blob/48e364cd8d7f7d43be324af56dfb462c8f6c1d91/tests/testthat/test-examples.R#L3

Thanks

**Comment by jimhester** [comment]
In general I would avoid having `testthat::test_examples()` in your tests. I actually do not think examples should be included in coverage statistics, but if you want to do so you can use `package_coverage(types = c("tests", "examples"))`, which will combine the test and example coverage. I ran just 'examples' and you can see your function is counted as covered.

<img width="918" alt="screenshot 2016-10-05 17 48 24" src="https://cloud.githubusercontent.com/assets/205275/19133012/3f33ae56-8b24-11e6-84d4-ffa28afabca0.png">

Also you may want to look at `cut()` as a replacement for `round_to_seq()` they seem to be doing largely the same task but `cut()` is at least a order of magnitude faster on simple benchmarks.

**Comment by gvegayon** [comment]
I see, so by default `package_coverage` is set to `"tests"`, does that means that it only includes lines that are evaluated within `test_that` (so `test_examples` won't be counted in)? That's what confuses me.

I understand why you suggest that examples should not be included in the stats, I rely on covering examples of functions that aren't so important (or are rather simple) so that I know for what parts of the package I have at least ran using examples. Will follow your suggestion and try to avoid doing so!

As for the `cut` function, thanks for pointing that out!, although in my case it won't work since intervals is not exactly what I'm doing in `round_to_seq`, e.g. while 1.2 and 1.8 would fit in the interval (1,2], I need those to be mapped to 1 and 2 respectively (sounds more like a work for round but instead of 1 and 2 I can have 1.1 and 2.3 as numbers to be mapped to =P) 
 
Thanks!

**Comment by jimhester** [comment]
Looking into this more there was actually a testthat bug, `test_examples()` did not work on installed packages, such as during R CMD check and when using covr. I sent https://github.com/hadley/testthat/pull/532 to fix the issue, which gives you the expected coverage.

One downside to this fix is the examples will now be run twice during R CMD check, since they were being inadvertently skipped previously.

**Comment by gvegayon** [comment]
Great! Thanks for the quick fix!
