### ISSUE TITLE
Local reporting or badging

### ISSUE THREAD

**Issue by jennybc** [jimhester/covr#207]
I have a package in a private repository, but I still want to monitor its test coverage. On principle and in anticipation that it will eventually become public and I'll use the usual approach & badge.

This seems like a nice thing to put into README.Rmd and then force myself to knit to README.md via habit or a git hook.

Could `covr` offer some attractive reporting of coverage that is achieved entirely locally vs. travis + coveralls? It feels like test coverage reporting and continuous integration should be somewhat separable.

**Comment by jimhester** [comment]
One thing you can do now is use codecov.io (which gives you one free private repository) and call `covr::codecov(token = 'xyz')` with a codecov token which is generated at https://codecov.io/account/gh/jennybc/access, which will allow you run coverage locally and send the reports. Then you can simply switch to using travis once the repository is public.

You may also be able to use reports generated from `covr::report()`, then only trick would be getting the javascript dependencies / css either inlined in the report or used from external rather than local resources.

**Comment by jennybc** [comment]
If you have a very generous definition of "attractive", which apparently I do, simply putting this in a chunk in `README.Rmd` is better than nothing. It shows when the coverage was run in terms of time and commit:

<pre><code>```{r}
Sys.time()
git2r::repository(".")
covr::package_coverage(".")
```
</code></pre>

``` r
Sys.time()
#> [1] "2016-07-18 16:59:49 CEST"
git2r::repository(".")
#> Local:    master /Users/jenny/rrr/githug0/
#> Remote:   master @ origin (https://github.com/jennybc/githug0.git)
#> Head:     [c056bc1] 2016-07-18: low tech test coverage monitoring
covr::package_coverage(".")
#> githug Coverage: 100.00%
#> R/git_config.R: 100.00%
#> R/githug_list-class.R: 100.00%
#> R/repo-path.R: 100.00%
#> R/utils.R: 100.00%
```

I still plan to try your other suggestions.

**Comment by jimhester** [comment]
We could probably write a print function to return a markdown formatted table.

```r
markdown <- function(x, group = c("filename", "functions"), by = "line", ...) {

  if (length(x) == 0) {
    return(invisible(x))
  }
  group <- match.arg(group)

  df <- tally_coverage(x, by = by)

  if (!NROW(df)) {
    return(invisible(x))
  }

  percents <- tapply(df$value, df[[group]], FUN = function(x) (sum(x > 0) / length(x)) * 100)

  overall_percentage <- percent_coverage(df, by = by)

  paste0("|file|percents|\n|----|----|\n",
    paste0("|Overall|", format(overall_percentage, digits = 4), "%|\n"),
    paste0("|", names(percents), "|", format(percents, digits = 4), "%|", collapse = "\n"), "\n")
}

cat(markdown(covr::package_coverage("~/p/githug")))
```

|file|percents|
|----|----|
|Overall|64.63%|
|R/gh_pat-username.R|100.00%|
|R/gh_repo_list.R|  0.00%|
|R/git_HEAD.R| 87.50%|
|R/git_add-commit.R|100.00%|
|R/git_branch.R|100.00%|
|R/git_config.R|100.00%|
|R/git_ignore.R|  0.00%|
|R/git_init.R|100.00%|
|R/git_log.R|100.00%|
|R/git_status.R|100.00%|
|R/git_utils.R| 28.57%|
|R/githug_init.R|  0.00%|
|R/githug_list-class.R| 33.33%|
|R/githug_utils.r|  0.00%|
|R/rpath-class.R| 96.30%|
|R/utils.R| 77.42%|

**Comment by cjyetman** [comment]
Any thoughts about adding and exporting a `markdown()` function like this? This could be very useful with GitHub Actions's new-ish [markdown "Job Summaries"](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/).

for example:
``` yaml
      - name: test-coverage
         run: |
           markdown <- function(x, group = c("filename", "functions"), by = "line", ...) {
             if (length(x) == 0) {
               return(invisible(x))
             }
             group <- match.arg(group)

             df <- covr::tally_coverage(x, by = by)

             if (!NROW(df)) {
               return(invisible(x))
             }

             percents <- tapply(df$value, df[[group]], FUN = function(x) (sum(x > 0) / length(x)) * 100)

             overall_percentage <- covr::percent_coverage(df, by = by)

             paste0("|file|percents|\n|----|----|\n",
               paste0("|Overall|", format(overall_percentage, digits = 4), "%|\n"),
               paste0("|", names(percents), "|", format(percents, digits = 4), "%|", collapse = "\n"), "\n")
           }
           system(paste0('echo "', markdown(covr::package_coverage()), '" >> $GITHUB_STEP_SUMMARY'))
         shell: Rscript {0}
```

achieves:
<img width="641" alt="Screenshot 2022-11-24 at 11 08 16" src="https://user-images.githubusercontent.com/1708872/203757657-a03344bf-fc4f-4dc5-a0e0-f1cbeec55ac6.png">

but (obviously?) this would be nicer:
``` yaml
      - name: test-coverage
         run: system(paste0('echo "', covr::markdown(covr::package_coverage()), '" >> $GITHUB_STEP_SUMMARY'))
         shell: Rscript {0}
```

**Comment by jimhester** [comment]
@cjyetman I think that is a good idea, could you open a new issue so it doesn't get lost.
