### ISSUE TITLE
package_coverage(<source_pkg_dir>) giving quite a few wrong '0%' coverage for `R/*.R`

### ISSUE THREAD

**Issue by mmaechler** [jimhester/covr#208]
I'm running  `package_coverage()` on my computer on my package source and (after a while, we have many tests) get a report in my (ESS) R console, nicely coloring the percentages for each source file.
The result points to  13 R/*.R and 5 src/*.c  files with 0% coverage.
For some of them I'm 100% sure that their functionality is at least partly covered in \examples{..}  which are *not* inside a \donttest{} or \dontrun{}...

The package is not small and has quite a history (and 2 JSS publications) and has always been on R-forge, not github, with landing page http://copula.r-forge.r-project.org  and direct access to a (slightly outdated) tarball via
http://download.r-forge.r-project.org/src/contrib/copula_0.999-15.tar.gz

For me, package_coverage("...path..to../copula")
reports (after many minutes!)  0% coverage e.g.,  for  `R/rotCopula.R`  whereas it is obivous that
`man/rotCopula.Rd` contains quite a few examples that exercise the code defined in the R file.

**Comment by jimhester** [comment]
Ok I will take a look and see if I can work out what is going wrong.

**Comment by jimhester** [comment]
The defaults for `package_coverage()` only run test files, not examples, so you need to pass `type = 'examples'` (not sure if you were already doing so).

On my machine using devel version of covr I see the following results

```r
package_coverage("copula")
# 44.26% overall coverage - 16 uncovered R files, 9 uncovered C files

package_coverage("copula", type = "examples")
# 66.67% overall coverage - 4 uncovered R files, 0 uncovered C files

package_coverage("copula", type = c("tests", "examples"))
# 73.92% overall coverage - 4 uncovered R files, 0 uncovered C files
```

**Comment by mmaechler** [comment]
Thank you!
 No, I was not setting `type` ... assuming that the default would be what you have as third example above.... (and what about "vignettes" - they are also run via  'R CMD check' ... so I could argue they should also belong to the default... After all it's  R CMD check that is run daily on CRAN and regularly on bioconductor and similarly frequently on Travis for some packages even before they are on CRAN
