### ISSUE TITLE
`R CMD check --run-dontcheck` -- equivalent for covr

### ISSUE THREAD

**Issue by mmaechler** [jimhester/covr#209]
Not urgent, but would nice:  If you have `\dontcheck{...}` sections in your help examples, typically because checking takes too much time,  recent versions of  `R CMD check` remind you to run  regularly / occasionally
`R CMD check --run-dontcheck`  so that these examples are run (and thereby tested) as well.

and there is a even less important    `--run-dontrun`  option to  `R CMD check`.

It would valuable to be able to also measure coverage when these additional examples are run.

**Comment by jimhester** [comment]
covr uses `tools::testInstalledPackage()` to run the examples and passes `...` to it. `testInstalledPackage()` in turn passes its `...` onto `tools:::.createExdotR()`. That function has `commentDontrun = TRUE` and `commentDonttest = TRUE` by default, but if you set those arguments to FALSE those sections won't be commented out.

So you should be able to do this with

```r
cov <- package_coverage(type = "examples", commentDonttest = FALSE)
```

**Comment by mmaechler** [comment]
thank you, Jim, very belatedly!
