### ISSUE TITLE
Include .Rbuildignore esclusions when collecting files for coverage

### ISSUE THREAD

**Issue by giupo** [jimhester/covr#216]
I tried using patterns when excluding a directory but from docs it looks like the param `line_exclusions` (of function `covr::package_coverage`) makes exclusions on a filename basis, ignoring patterns (es: `"packrat/**/*"`, `"packrat/*"`).  Am I missing something here? 

Wouldn't be easier to exclude files as stated in the standard `.Rbuildignore` file of every R package?

**Comment by jimhester** [comment]
The exclusions are regular expressions, not wildcards, you need to use `packrat/.*` to exclude all files in the packrat directory, but this should not be necessary only source files in `R/` and `src/` are going to be in your coverage results...

**Comment by giupo** [comment]
In my case, this is not working: I fear that there's some mess in my packages and their dependencies. 

However, covr (I dunno why, since I've made up a testing package, https://github.com/giupo/testCovrPackrat and there is not happening) keeps on picking up `.h` and `.cpp` files from `Rcpp` library which is stated as a dependency despite whatever I specify to the `line_exclusions` param.

**Comment by artemklevtsov** [comment]
The same problem [here](https://gitlab.com/artemklevtsov/benchr/builds/3707565): `line_exclusions` with regex not working.

**Comment by giupo** [comment]
My personal issue is in cojunction with `packrat`, and I've found a dumb workaround:
`covr::package_coverage(line_exclusions=file.path("packrat", list.files(path="packrat", recursive=T)))`

That bloated invocation forces to exclude every single file under packrat directory.
Works for me and hope this helps.
