### ISSUE TITLE
covr not probably tracing back a function

### ISSUE THREAD

**Issue by FrankPortman** [jimhester/covr#218]
Link to repo: https://github.com/FrankPortman/bayesAB

At the time of writing, my repo has 0.61% coverage. In [this test file](https://github.com/FrankPortman/bayesAB/blob/master/tests/testthat/test-bernoulli.R) you can see that I am calling the function `bayesTest` with multiple parameters. `bayesTest` then dispatches to `bayesBernoulliTest` (as evidenced by it passing all tests) although none of this code is considered covered by `covr`.

**Comment by jimhester** [comment]
@FrankPortman It looks like it is showing the correct coverage (100% for bayesBernoulliTest) now (https://codecov.io/gh/FrankPortman/bayesAB/src/e816e8966ad58b8b9bdd85d96695ba766f8f7afb/R/bayesBernoulliTest.R), has this been issue been resolved?

**Comment by FrankPortman** [comment]
@jimhester seems resolved now because of [this diff](https://github.com/FrankPortman/bayesAB/commit/dd0c1d9bee6e815b9e4b9403c91e61e5485623bf). `covr` didn't like tracing functions back outside of the function call itself.

**Comment by jimhester** [comment]
This is related to https://github.com/jimhester/covr/issues/113, in general covr assumes functions defined in the package are going to be in the package namespace directly. 

In terms of how things work https://github.com/jimhester/covr/blob/master/vignettes/how_it_works.Rmd has some information, but nothing that addresses this particular issue directly IIRC.
