### ISSUE TITLE
No coverage on .hpp files?

### ISSUE THREAD

**Issue by cdeterman** [jimhester/covr#226]
I have some c++ header files that I use extensively within my package.  Yet, the resulting coveralls (or codecov) show 0% of lines covered by my tests.  You can see this [here](https://coveralls.io/github/cdeterman/gpuR) primarily referring to the `dynEigenMat.hpp` file which is used in at least half of my unit tests.  Is this something to be expected when using classes in headers or did I somehow miss something?  Thanks for any assistance.

**Comment by Enchufa2** [comment]
I think this is related to #219 and #220. Please, try it out using [my fork](https://github.com/Enchufa2/covr) to see if #220 fixes your problem.

**Comment by cdeterman** [comment]
@Enchufa2 your fork does appear to fix the problem.  I look forward to the pull request, until then I will likely use your fork.

**Comment by Enchufa2** [comment]
Ok, thanks for the verification.

**Comment by Enchufa2** [comment]
@cdeterman I've verified that commit 586e65e fixed the problem, and @jimhester is going to close this issue and the PR. I'm going to remove my fork, so please switch back to Jim's repo.

**Comment by cdeterman** [comment]
@Enchufa2 excellent, thank you for the update.
