### ISSUE TITLE
report depends on temporary files

### ISSUE THREAD

**Issue by kforner** [jimhester/covr#228]
Hi,
When a html report is generated using report(cov, "foo.html"), this foo.html references temporary files, that will be deleted when the R process which generated the report exits.

So you can not view the report after, and you must have an interactive session. 
It could be nice to have an option (e.g. dir=tempfile()) to specify where to save these files.

**Comment by jimhester** [comment]
`report.coverage` does have a `file=` option for the output file, that can be whatever you want. This is documented in the generic's documentation `?report`.

I changed `report()` to a simple function which should make this more discoverable (f7446ce826cd86cc405541cfdd37850736f06ca3)

**Comment by kforner** [comment]
I'm not talking about the generated file itself, but about the temporary file it references, i.e.:
```
<script src="/tmp/Rtmp7go8l0/widgetbinding317ca47df3/datatables.js"></script>
```

**Comment by jimhester** [comment]
All of the html dependencies are in a `lib/` directory within the same directory as the html file.

**Comment by kforner** [comment]
oh, when did you implement this ? My current version (covr_2.1.0.9000) does not create this "lib" dir, and the line I mentioned was just grepped.
I tried the master version, but it crashes on my report:
```
> report(cov, file = 'foo.html')
Error in seq.default(df[i, "first_line"], df[i, "last_line"]) : 
  'from' must be of length 1

Enter a frame number, or 0 to exit   

1: report(cov, file = "foo.html")
2: to_shiny_data(x)
3: per_line(x)
4: seq(df[i, "first_line"], df[i, "last_line"])
5: seq.default(df[i, "first_line"], df[i, "last_line"])
```

**Comment by kforner** [comment]
Ok. I double checked and the new master solves the issue indeed. Great! I could not reproduce the report crash that I got previously with the master version, so never mind.
Thanks.

**Comment by jimhester** [comment]
Ok good to know!
