### ISSUE TITLE
Symbol not found: ___gcov_merge_add

### ISSUE THREAD

**Issue by dankelley** [jimhester/covr#231]
**Preamble.** I am new to `covr` (and `codecov` in general), so please excuse me if this is a silly question. I find that I get good results from `codecov` (via `github`) but the process is slow because my package takes 20 minutes to check.  I'd like to do local tests, without this delay (and without bothering my users by pushing code before it's ready, of course).

**Problem.** When I do a local test (with `covr` from CRAN or github, the latter installed within the past hour), I get an error as below.  Is it necessary that I install a separate library on my machine? I'd appreciate any help I could get with this, and I apologize if this question displays anomalous ignorance.
```
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/private/var/folders/rx/k1x_t_q12zb9hbjr4ldxmjc80000gn/T/Rtmp6AiG9x/R_LIBS12e89631002ef/oce/libs/oce.so':
  dlopen(/private/var/folders/rx/k1x_t_q12zb9hbjr4ldxmjc80000gn/T/Rtmp6AiG9x/R_LIBS12e89631002ef/oce/libs/oce.so, 6): Symbol not found: ___gcov_merge_add
  Referenced from: /private/var/folders/rx/k1x_t_q12zb9hbjr4ldxmjc80000gn/T/Rtmp6AiG9x/R_LIBS12e89631002ef/oce/libs/oce.so
  Expected in: flat namespace
 in /private/var/folders/rx/k1x_t_q12zb9hbjr4ldxmjc80000gn/T/Rtmp6AiG9x/R_LIBS12e89631002ef/oce/libs/oce.so
Error: loading failed
Execution halted
```

**Session Info**
```R
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.1

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] covr_2.2.1     oce_0.9-20     gsw_1.0-4      testthat_1.0.2

loaded via a namespace (and not attached):
 [1] digest_0.6.10   crayon_1.3.2    withr_1.0.2     R6_2.1.3        git2r_0.15.0   
 [6] magrittr_1.5    httr_1.2.1      curl_2.1        lazyeval_0.2.0  rex_1.1.1      
[11] devtools_1.12.0 tools_3.3.2     memoise_1.0.0   knitr_1.14    
```

**Comment by jimhester** [comment]
What package are you trying to run coverage on, what compiler are you using to compile the native code, what version is the compiler and what gcov executable is on your PATH. Likely this error is do to a missing gcov library when linking.

**Comment by dankelley** [comment]
The package I'm building is `oce` (at `github.com/dankelley/oce`); answers to the other questions are below the dashed line.

You are right: RStudio is not finding the `gcov` library. I installed `gcov` with `brew`, but have not discovered how to install the library to which `codecov` is to be linked (it's not in `/usr/lib` or in `/usr/local/lib`).

I'll play with this a bit and report back if I find the magic recipe for OSX.  Thanks very much for the quick reply.

The answers to your version questions are below. I'm trying the builds with Rstudio.

```
$ clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ gcov --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
  Optimized build.
  Default target: x86_64-apple-darwin16.3.0
  Host CPU: ivybridge

$ which gcov
/usr/bin/gcov
```

**Comment by jimhester** [comment]
I can reproduce this on my MacOS machine as well, I think the issue is trying to compile coverage with gcc gfortran and clang++. If you turn off coverage for the fortran files or use the gcc toolchain it works for me.

```r
# To turn off the fortran coverage just remove `FFLAGS` from the `covr.flags` option
options(covr.flags = c(CFLAGS = "--coverage", CXXFLAGS = "--coverage", LDFLAGS = "--coverage"))
```

**Comment by dankelley** [comment]
This is brilliant. Thanks *very* much. I'll close this, on the assumption that you prefer reporters to close things. Thanks so much for the help!
