### ISSUE TITLE
Upload to codecov timeout on Travis

### ISSUE THREAD

**Issue by MarkEdmondson1234** [jimhester/covr#233]
Hello,

Thanks for your aid on another thread my tests do not timeout, but now the final step of uploading to codecov does - is there a way to call it in a similar manner?  

I have details here of the last successful and first failed commit:
https://github.com/cloudyr/googleComputeEngineR/issues/26

Perhaps its if an overall 20 min timeout is reached?

**Comment by asardaes** [comment]
Can I join the discussion and ask if this is a confirmed bug? I'm seeing the same error [here](https://travis-ci.org/asardaes/dtwclust/jobs/222566719). It only started happening after adding `travis_wait`, and based on [this log from a different package](https://travis-ci.org/lgatto/MSnbase/jobs/220995263), it happens only if specific arguments are passed to `codecov`.
