### ISSUE TITLE
OS dependent code

### ISSUE THREAD

**Issue by gaborcsardi** [jimhester/covr#235]
This is just a question, in case you were thinking about this already.

How should I handle OS specific code? I have some code that only runs on windows, and some other that only runs on non-windows, and I really like 100% coverage. :)

Is there a way to 
* ignore code conditionally, and/or
* merge two coverage results into one, and/or
* handle this with codecov?

**Comment by jimhester** [comment]
Codecov will automatically merge multiple coverage reports from the same commit, so you should be able to run `covr::codecov()` separately on appeveyor and travis and get the merged coverage.

**Comment by gaborcsardi** [comment]
Oh, sweet, I did not know that! Perfect!
