### ISSUE TITLE
Feature request: Test whether non-default argument has been used 

### ISSUE THREAD

**Issue by HughParsonage** [jimhester/covr#239]
Can `covr` be used to test whether an argument has been used with a non-default value?

```r
#' @param x,y,z Numbers to add
#' @return The sum of x,y,z.
 
add <- function(x = 0, y = 0, z = 0){
 x + y 
}
```

or 

```r
#' @param x,y,z Numbers to add
#' @return The sum of x,y,z.
 
add <- function(x = 0, y = 0, z = 0){
 x + y + 0 * z
}
```

with test:

```r
expect_equal(add(2, 3), 5) 
```

My code would be marked as having 100% coverage, despite having a serious bug.

**Comment by jimhester** [comment]
No it cannot and likely will never be able to do so. 100% coverage does not mean 100% correct and you should not expect it to mean such.
