### ISSUE TITLE
package_coverage() does not check in the testthat directory

### ISSUE THREAD

**Issue by alanault** [jimhester/covr#240]
When running package_coverage(), it would not see my primary unit tests I run with testthat, it would only see my examples (with type="examples").

However, it appears this is because my tests live in the /tests/testthat directory; if I copy them into the parent directory (/tests) covr correctly seems then and reports the coverage.

Is there an option I should be passing so that covr looks in the sub-directory of test, or something else I'm missing?

**Comment by jimhester** [comment]
There is something you are missing. I would need to see the package exactly what is wrong but either the tests/testthat.R file is not correct or the tests files are not named correctly. Make sure your package is following this exactly https://github.com/hadley/testthat/blob/master/README.md#integration-with-r-cmd-check

**Comment by alanault** [comment]
Hi Jim - thanks for the super fast response!

This was exactly it. I hadn't realised the importance of the testthat.R file which sits in the main test directory. Making sure this was completed fixed everything.

Thank you

Alan

**Comment by jimhester** [comment]
Great, glad you figured it out!
