### ISSUE TITLE
statistics of boot object are truncated

### ISSUE THREAD

**Issue by wligtenberg** [jimhester/covr#244]
I can run my tests just fine with devtools and R CMD check.
When I run it using covr, I get an error in the tests.

The test is expect_equal on a boot object, object create with boot::boot(...).
The issue is only with the statistic item in the list.
Printing the stored result with the result that is generated when running covr, reveals that the code that is stored in there seems truncated.

stored result prints as:
```
function(dt, i){
    # make the selection
    dt <- dt[i, ]
    reference_batch <- dt[
      product == "reference",
      .SD,
      .SDcols = c("time", "dissolution")]
    test_batch <- dt[product == "test", .SD, .SDcols = c("time", "dissolution")]
    # Fix batches
    reference_batch[, replicate := seq_len(nrow(.SD)), by = time]
    test_batch[, replicate := seq_len(nrow(.SD)), by = time]
    return(
      dissolution_f2(
        reference_batch = reference_batch,
        test_batch = test_batch))
  }
```
result when running covr prints as:
```
<environment: 0x39bbff0>
function(dt, i){
    # make the selection
    dt <- dt[i, ]
    reference_batch <- dt[
      product == "reference",
      .SD,
      .SDcols = c("time", "dissolution")]
    test_batch <- dt[product == "test", .SD, .SDcols = c("time", "dissolution")]
    # Fix batches
    referenc
```
What you see there is the code of my wrapper function.

I know this is not a reproducible example, but I am willing to dig into the code to debug. Or work on a minimal example.
I would not even know right away how to minimize this example.

**Comment by wligtenberg** [comment]
I think the issue is might be in a difference between testthat::test_check and devtools::check.
I have not yet been able to deduce much else.

**Comment by wligtenberg** [comment]
@jimhester As requested I made a small example available here:
https://github.com/wligtenberg/covrtest

**Comment by jimhester** [comment]
An unrelated issue is it looks like you have an extra import [dissolution](https://github.com/wligtenberg/covrtest/blob/73e21bfe3b067da94f5c65049a37e2c0c5899b2f/R/covr_test.R#L5), removing that and re-documenting allows the package to compile.

The true issue is the boot objects include the statistic function and if you modify your print statements to print the function body `print(body(tmp$statistic))` you will be able to see the difference.

```r
> test_check("covrtest")
{
    return(1)
}
{
    {
        covr:::count("covr_test.R:16:5:16:13:5:13:18:18")
        return(1)
    }
}
1. Failure: testme should produce an issue (@test-testme.R#8) ------------------
`tmp` not equal to `f2_boot`.
Component “statistic”: target, current do not match when deparsed
```

The default print method for functions uses the source reference to print if one exists. Covr modifies the function body but does not modify the source references, so simply printing the function will not show the difference.

The short answer is this is working as expected, if you want to compare boot objects you need to compare them without the statistic function, as it will be correctly altered by covr.

**Comment by wligtenberg** [comment]
@jimhester Well, the thing is, it works fine with running devtools::test()
Which I use normally to run tests, so it is unexpected, that it then fails when using covr, not?

**Comment by jimhester** [comment]
No? `devtools::test()` doesn't modify the function bodies like covr does, this is working as expected.

**Comment by wligtenberg** [comment]
@jimhester I agree that it is expected, if you know how covr works.
However, for a lot of users of the package it would come as an unwelcome surprise if the tests they have been running just fine, suddenly fail when they want to use covr.

Could this (maybe not so big issue) be resolved by having a special deparse function, that will remove the things added by covr?
Because I do think we should try not to add extra constraints to the tests people can write while using covr (as much as possible).

**Comment by jimhester** [comment]
The deparsing issue you observed is actually just cosmetic and comes from testthat. The failure comes from a test for equality between the function saved before running covr and one during a covr run. If the test function was generated during the covr run as well there would be do discrepancy.

Any fix for this would cause other problems, we could set a class on covered functions, but this would cause failures if people explicitly test for classes on a function. We could provide an alternative equality method, which would remove the counts, but that would cause failures if the package also provided a different equality method.

I think this is just something you have to work around.

**Comment by wligtenberg** [comment]
Thank you for the extra explanation, I can see how there is no good fix for this.
I might create a function to compare boot objects then and maybe release that as a package, so people can use that. Or could/should we add such a function in covr?

**Comment by wligtenberg** [comment]
wrote the function and created PR on testthat, because I think it is best placed there.
https://github.com/hadley/testthat/pull/568
