### ISSUE TITLE
Problem using covr in testthat testcases

### ISSUE THREAD

**Issue by fangly** [jimhester/covr#248]
Hi,

As part of my package's testthat test suite, I would like to include testcases for code coverage (covr version 2.2.2), e.g. that the average code coverage is over 90%.

I have written a simple file for this purpose at tests/testthat/test_coverage.R:
```
pkgRoot <- "../.."
cat("Code coverage for package at", normalizePath(pkgRoot), "\n")
exclusions <- list("tests/testthat/test_coverage.R")
cov <- covr::package_coverage(pkgRoot, line_exclusions=exclusions)
testthat::expect_gt(covr::percent_coverage(cov), 90L)
````

But I get an error when running the tests:
```
> devtools::test()
Loading s002
Testing s002
constants: ............................
Code coverage for package at C:\qc\zoe_home\s002_K010_M2_support
Error: Failure in `C:/Users/u0000234/AppData/Local/Temp/RtmpuW5w6q/R_LIBS25483c3274ac/s002/s002-tests/testthat.Rout.fail`
[...]
```

And the file testthat.Rout.fail contains:
```
> test_check("s002", reporter="summary")
[...]
constants: ............................
Code coverage for package at C:\Users\u0123456\AppData\Local\Temp\RtmpuW5w6q\R_LIBS25483c3274ac\s002Fehler in file(con, "r") : kann Verbindung nicht öffnen
Ruft auf: test_check ... eval -> <Anonymous> -> add_hooks -> readLines -> file
Zusätzlich: Warnmeldungen:
1: Ausführung von Kommando '"C:/PROGRA~1/R/R-32~1.5/bin/x64/R" CMD INSTALL --example --install-tests --with-keep.source --no-multiarch -l "C:\Users\u0000234\AppData\Local\Temp\Rtmpopq5eH\R_LIBS104875b32dd" "C:/Users/u0000234/AppData/Local/Temp/RtmpuW5w6q/R_LIBS25483c3274ac/s002"' ergab Status 1 
2: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package 'C:/Users/u0000234/AppData/Local/Temp/RtmpuW5w6q/R_LIBS25483c3274ac/s002' had non-zero exit status
3: In file(con, "r") :
  kann Datei 'C:/Users/u0000234/AppData/Local/Temp/Rtmpopq5eH/R_LIBS104875b32dd/s002/R/s002' nicht öffnen: No such file or directory

DONE ===========================================================================
Ausführung angehalten
```

It seems like covr installs my s002 package in a temporary location, and runs its test suite... which includes my coverage tests... which requires installing my package in a temporary location. This is a chicken and egg problem!

I have tried to add the test_coverage.R file as an exclusion, but this did not achieve what I hoped it would (the file is excluded for coverage calculations, not for package installation). Is there another way to achieve my goals? If not, then perhaps it would be a good idea to:
1. have package_coverage() detect that it is contained in a test file
2. delete this test file from the temporary installed package

Cheers,
Florent 

PS/ If I just run remove the file test_coverage.R and paste its code in an R terminal, everything goes well.

**Comment by jimhester** [comment]
If you are using either codecov.io or coveralls they both support failing the build if the coverage falls below a certain amount. But presumably you cannot use those services.

I think the way to go is to condition on an environment variable in your tests, which will protect against the recursive calls.

```r
local({
  if (!isTRUE(Sys.getenv("COVR_HAS_RUN", FALSE))) {
    Sys.setenv("COVR_HAS_RUN" = TRUE)
    on.exit(Sys.setenv("COVR_HAS_RUN" = FALSE))
    pkgRoot <- "../.."
    cat("Code coverage for package at", normalizePath(pkgRoot), "\n")
    exclusions <- list("tests/testthat/test_coverage.R")
    cov <- covr::package_coverage(pkgRoot, line_exclusions=exclusions)
    testthat::expect_gt(covr::percent_coverage(cov), 90L)
  }
})
```

**Comment by fangly** [comment]
I was thinking about a more complex workaround, but I like your suggestion way better, Jim. Thanks a lot!
You should definitely add it to your README.md file.
Cheers,
Florent

**Comment by fangly** [comment]
This would be better though if the `package_coverage` function would take care of setting this environment variable. Any reason it could not be implemented?
