### ISSUE TITLE
Code coverage pretty printer for terminals?

### ISSUE THREAD

**Issue by gaborcsardi** [jimhester/covr#250]
Using `gaborcsardi/prettycode`? Or `jimhester/highlite`? `prettycode` highlighting is nicer, though, :) and it is a very lightweight dependency. 

Would you want this in `covr`? We could nicely highlight the covered and not-covered lines, etc...

**Comment by jimhester** [comment]
I am not sure it is worth the effort if we already have the HTML report.

It might be cool to query codecov.io in prettycode or lookup and automatically highlight the covered lines when you print the function definition though... Basically do the same thing the codecov chrome plugin died on the terminal

**Comment by gaborcsardi** [comment]
codecov lookup is relative slow, so I would rather not do that for printing functions. Also, I typically have a different version locally when I am developing sg, so I would need to so `git diff`, query GitHub, etc. My use case is when you do `zero_coverage` and then get sg. like this:
```
210                    R/api.R                        keyring_create   78     0
214                    R/api.R                        keyring_create   80     0
219                    R/api.R                        keyring_create   82     0
```
and I want to know what those lines are.
