### ISSUE TITLE
Covr "cannot open the connection"

### ISSUE THREAD

**Issue by dirmeier** [jimhester/covr#252]
Dear all,

when I am trying to call

```r
covr::codecov()
```
it throws the following error:

```r
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ...’ had non-zero exit status
2: In file(con, "r") :
  cannot open file '/private/var/folders/cx/...': No such file or directory
```

The checks/builds on Travis work fine, only the calculation of coverage does not work. I am using `covr` in plenty of other packages (with Rcpp/C++ extensions), and this is the first time I encountered this issue. Am I missing something or so? 

Thanks in advance, Simon

**Comment by jimhester** [comment]
The package installation failed. Run `package_coverage(quiet=FALSE)` locally to diagnose the problem.

**Comment by dirmeier** [comment]
Thank you. Doing this showed that the issue lied with not finding gfortran.
