### ISSUE TITLE
Change of covr license to GPL-3

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#256]
covr is currently MIT licensed, however a strict reading of the GPL-2 license for
dependency [withr](https://cran.r-project.org/web/packages/withr/index.html)
(which is GPL >= 2) would require covr to also be GPL-2 or GPL-3. Oracle's'
legal representation suggested `LICENSE MIT + file LICENSE + Portions GPLv3 with Additional Permission |
GPLv3`, but as this is a non-standard license it will be flagged by CRAN and
create additional maintenance hassles going forward.

Because of these concerns I now feel the most expedient thing to do is to
change the covr license to GPL-3, however in order to do so I will need
approval from all contributors (listed below). Please reply to this issue with
either
 - I accept the change of covr license to GPL-3
 - I reject the change of covr license to GPL-3

We can only change license if we get acceptance from all contributors.

- [x] - Jim Hester (@jimhester)
- [x] - Kirill Müller (@krlmlr)
- [x] - Henrik Bengtsson (@HenrikBengtsson)
- [x] - Steve Peak (@stevepeak)
- [x] - Kirill Sevastyanenko (@kirillseva)
- [x] - Jon Clayden (@jonclayden)
- [x] - Robert Flight (@rmflight)
- [x] - Eric Brown (@enbrown)
- [x] - Brodie Gaslam (@brodieG)
- [x] - Will Beasley (@wibeasley)
- [x] - Robert Krzyzanowski (@robertzk)
- [x] - Markus Wamser (@wamserma)
- [x] - Willem Ligtenberg (@wligtenberg)
- [x] - Karl Forner (@kforner)
- [x] - Gergely Daróczi (@daroczig)
- [x] - Jouni Helske (@helske)
- [x] - Kun Ren (@renkun-ken)
- [x] - Jeroen Ooms (@jeroen)
- [x] - Ken Williams (@kenahoo)
- [x] - Chris Campbell (@CSJCampbell)

Thank you for your time and I apologize for the disturbance, thank you again
for contributing to covr.

**Comment by kforner** [comment]
I accept the change of covr license to GPL-3.

Regards,
Karl

**Comment by wibeasley** [comment]
I accept the change of covr license to GPL-3 -@wibeasley

**Comment by helske** [comment]
I accept the change of covr license to GPL-3.

**Comment by gaborcsardi** [comment]
@jimhester How about getting rid of the `withr` dependency?

**Comment by rmflight** [comment]
I accept the change to GPL-3

However, I thought it was possible to call GPL packages within non-GPL packages and use a non-GPL license in the calling package without any issues.

**Comment by jimhester** [comment]
@gaborcsardi I cannot change the withr dependency because it inherits GPL>=2 from code adapted from devtools, and devtools inherits GPL>=2 from code adapted from R itself. I looked into removing the withr dependency, but I would end up just duplicating the code locally, which did not really seem within the letter of the licenses either.

**Comment by gaborcsardi** [comment]
@jimhester 

:( Yeah, somebody else would need to rewrite those functions, just from the docs....

Btw. how about calling base R functions? Those are GPL, too......

**Comment by kirillseva** [comment]
@jimhester why not just reimplement those functions? I'm with @gaborcsardi on this one
```r
used_withr_functions <- c(
  "with_dir",
  "with_makevars",
  "with_envvar",
  "with_output_sink",
  "with_options"
)
```

Honestly, this basic functionalities should be built into `R` itself, or be licensed as permissively as possible since they happen to be small, convenient building blocks that people tend to agree upon

**Comment by jimhester** [comment]
@rmflight I think different people / organisations have different viewpoints on the licensing issue. Myself, RStudio and the R community in general seem to feel like MIT licensed packages can depend on GPL licensed packages without an issue, as the packages are obtained separately and assembled on the users computer. Oracle is taking a stricter view and insists on the package having to be GPL licensed if any package is GPL licensed and as @gaborcsardi mentioned R itself is GPL-2|GPL-3 licensed, so ¯\_(ツ)_/¯.

In either case covr is a direct dependency on very few packages, even packages which have covr in `Suggests:` do so mainly by convenience, as covr is a developer tool not typically used when building or testing the package on CRAN or shipped with the package to users. So regardless of the covr license I do not thing it affects downstream dependencies.

I have been trying to deal with this license issue in the R Coverage Working Group for almost a full year now and see this license change as the best way to move forward.

**Comment by kirillseva** [comment]
@jimhester would this approach work? https://github.com/jimhester/covr/pull/257
or is using withr's API is also a violation of copywrite

**Comment by HenrikBengtsson** [comment]
> I have been trying to deal with this license issue in the R Coverage Working Group for almost a full year now and see this license change as the best way to move forward.

Is that where Oracle comes in to the picture? I was bit confused why Oracle was mentioned at all.

**Comment by jimhester** [comment]
Yes, most of the working group is from Oracle (https://wiki.r-consortium.org/view/Code_Coverage_Tool_for_R), they are also responsible for https://github.com/jimhester/covr/pull/247 to add icc support, which would require some sort of license resolution to be merged.

**Comment by enbrown** [comment]
I accept the change of covr license to GPL-3.

On Fri, Mar 31, 2017 at 12:49 PM, Henrik Bengtsson <notifications@github.com

**Comment by daroczig** [comment]
I accept the change of covr license to GPL-3

**Comment by jeroen** [comment]
I accept the change of covr license to GPL-3

**Comment by kirillseva** [comment]
Giving control over essential R tooling to Oracle... What could go wrong? :)

**Comment by kirillseva** [comment]
I accept the change of covr license to GPL-3

**Comment by robertzk** [comment]
I accept.

**Comment by krlmlr** [comment]
I accept the change of covr license to GPL-3

**Comment by HenrikBengtsson** [comment]
I accept the change of covr license to GPL-3 (or whatever @jimhester prefers in the end).

Two thoughts:
* If a change is badly needed and urgent, the decision can be procrastinated by keeping a dual licenses on GitHub and only make the license change on CRAN.  (Not optimal, but buys time if needed).

* If a rewrite of `withr` functions would be the preferred path, I could look into doing that / contributing such because I'm not contaminated by withr at all (= true); I've got old-style `withYadayada()` functions in [R.utils](https://github.com/HenrikBengtsson/R.utils/tree/master/R) that partly overlap and for the longest I considered making a `with` package - eventually `withr` came around.

In the bigger picture:
Although not the best place to discuss this, I don't know a better place to bring it up: are there are other legal voices involved in the 'Code Coverage Tool for R' working group than Oracle's?  And in the bigger picture, in The R Consortium in general?  If only single legal voice is speaking, and others are "I don't know enough about this so I'll just accept because they probably know what they're talking about and I don't want to be the one bothering others", then maybe this should be brought up as an concern to the R Consortium Board.

**Comment by brodieG** [comment]
I accept the change of covr license to GPL-3

**Comment by kenahoo** [comment]
I'm such a minor contributor to 'covr' that I definitely wouldn't stand in
the way of whatever license change you need to make.

However, I don't particularly like that the GPL3 license essentially
virally bullies other packages into adopting its terms.  If there's a way
to avoid it, I'd definitely prefer that.

 -Ken

**Comment by jonclayden** [comment]
I accept the change of covr license to GPL-3.

I'm not a big fan of that license, but clearly a lot of discussion has already gone into this, so I'm happy for you to decide!

**Comment by wamserma** [comment]
I accept the change of covr license to GPL-3

**Comment by kenahoo** [comment]
To make things easier, having already voiced my displeasure about it, I'll also say:

   I accept the change of covr license to GPL-3.

 -Ken

**Comment by wligtenberg** [comment]
I accept the change of covr license to GPL-3.

**Comment by CSJCampbell** [comment]
I accept the change of **covr** license to GPL-3.

**Comment by jimhester** [comment]
@stevepeak, @renkun-ken, @rmflight Could you please respond one way or the other to this issue? As mentioned we cannot change the license without full approval.

**Comment by rmflight** [comment]
I am @rmflight, and I already [replied above](https://github.com/jimhester/covr/issues/256#issuecomment-290774978). 

I accept the change of license of covr to GPL-3.

**Comment by jimhester** [comment]
Sorry Robert, I missed checking off your approval, thanks for replying again!

**Comment by stevepeak** [comment]
I accept the change of covr license to GPL-3
Thank you @jimhester

**Comment by renkun-ken** [comment]
I accept the change of covr license to GPL-3.

Thanks you @jimhester!

**Comment by jimhester** [comment]
Thanks again to everyone for responding to this request and for contributing to covr!
