### ISSUE TITLE
Last line of cpp function reported as not covered

### ISSUE THREAD

**Issue by rorynolan** [jimhester/covr#258]
This happened to me on this function, never happened to me on any other.
<img width="652" alt="screen shot 2017-04-09 at 11 31 08" src="https://cloud.githubusercontent.com/assets/20400852/24836635/74e45f06-1d18-11e7-9346-202c01064f95.png">

Here's the code if you want it:

```c++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double ReflectIndexMed(NumericVector vec, int ind, std::string side) {
  int n = vec.size();
  double out = NA_REAL;
  double med;
  int dist_to_end;
  int dist_to_go;
  double median_dist;
  if (side == "left") {
    NumericVector left = vec[seq(0, ind - 1)];
    med = median(left);
    dist_to_end = ind;
    dist_to_go = 2 * dist_to_end;
    median_dist = 1 + 0.5 * (dist_to_end - 1);
    out = vec[ind] + dist_to_go / median_dist * (med - vec[ind]);
  } else if (side == "right") {
    NumericVector right = vec[seq(ind + 1, n - 1)];
    med = median(right);
    dist_to_end = (n - 1) - ind;
    dist_to_go = 2 * dist_to_end;
    median_dist = 1 + 0.5 * (dist_to_end - 1);
    out = vec[ind] + dist_to_go / median_dist * (med - vec[ind]);
  }
  return out;
}
```

**Comment by jimhester** [comment]
What compiler and version are you using? This is a commonly reported issue for [gcc gcov]( https://www.google.com/search?q=gcov+closing+brace)

**Comment by rorynolan** [comment]
I'm using clang

**Comment by jimhester** [comment]
There are similar issues with clang (https://sourceforge.net/p/ltp/mailman/message/34832676/), one suggestion from that thread is what is uncovered is exists from the function due to possible exceptions being thrown.

In any case this is what is being reported by the coverage tool, covr is translating them unaltered.

**Comment by rorynolan** [comment]
Thanks Jim, an exception was indeed being thrown, however I managed to fix the coverage by moving the initialisations of `left` and `right` to before the `if` statement. So I managed to fix the coverage issue like this before I found and fixed the exception. Take from that what you will.
Loving all your work including `covr` and your customer service is excellent!
