### ISSUE TITLE
Coverage of on-file-load R6 objects

### ISSUE THREAD

**Issue by schloerke** [jimhester/covr#259]
Hi Jim,

I'm trying to get coverage of functions that are executed/loaded when the corresponding R file is loaded.

Example screenshot from a package R file:
![screen shot 2017-04-25 at 3 43 01 pm](https://cloud.githubusercontent.com/assets/93231/25404528/59d98ef8-29ce-11e7-96c5-4a6e42f6bf12.png)

The object `ScalarTypeDefinition` is an R6 object and the function `coerce_float()` is used internally.  

This similar situation also occurs with regular, non-R6 functions that are used to create objects upon sourcing of the R file.

![screen shot 2017-04-25 at 3 48 59 pm](https://cloud.githubusercontent.com/assets/93231/25404664/d58fb676-29ce-11e7-8e6b-edf2e84aae75.png)

The red lines above must be called as it generates the green area.

I can come up with a minimal example if you'd like, but I think I'm missing a concept of when the covr code is injected / inspected.

Thank you for the help!

- Barret

**Comment by jimhester** [comment]
Yeah covr modifies the functions to add the tracing calls _after_ package loading, so if a function only run on load it is not going to be covered.

I think there are only a few options

1. Run the relevant code again in your tests. Not feasible for every case, but sometime you can just write a test to explicitly run the given code.
2. Remove the lines from coverage calculations with '#nocov start' '#nocov end' comments
3. Change covr to modify the code before installation of the temporary package. This is the most robust way but would require large changes and may not actually be feasible to accomplish.

The first option is the best solution if you can re-run the code, if not than 2. is your only real option. 3. I don't think is likely to happen, in some way covr is supposed to measure only the code that is run in your tests, which code run on load is not.

**Comment by schloerke** [comment]
Thank you for the help!  

So for #1, I would just `source()` the R file inside my tests? Or call the function directly?

Would moving the bad situations inside `.onLoad()` solve this? Or is covr inserted after that?

**Comment by jimhester** [comment]
Just call the function directly, the traces are inserted after `.onLoad()` IIRC.
