### ISSUE TITLE
zero coverage result is nonsensical

### ISSUE THREAD

**Issue by alexWhitworth** [jimhester/covr#262]
running `package_coverage()` on package [imputeMulti](github.com/alexwhitworth/imputeMulti) returns a status of 0% coverage.

this makes literally no sense to me, since I have dozens of unit tests which have been useful in package building to catch and fix several errors. I'm wondering if it has to do with my `tests/testthat` file, which purposefully don't run tests during the build. This is done because CRAN suggests only having tests that last < 1-2 minutes. And also because Travis.ci seems to have problems accessing non-exported functions within the `testthat` testing environment.

Here's is my `tests/testthat.R` file. **Any help would be appreciated!**

```
library(testthat)
library(imputeMulti)
library(parallel)

# test_check("imputeMulti")
```

**Comment by jimhester** [comment]
Well if you don't run the tests of course you are going to have no coverage.

You can use `testthat::skip_on_cran()` to skip long running tests on CRAN.

You need to make sure `devtools::check()` or `R CMD build . && R CMD check *tar.gz` work with your package before using covr.

**Comment by alexWhitworth** [comment]
Thanks--that was the question. I suppose more succinctly phrased as "Does `covr` depend on the `testthat`'s measure of running tests or does it run the tests via `devtools::test`?" `devtools:test`will run my tests (and pass them)... and yes, `devtools::check()` also passes

**Comment by jimhester** [comment]
It has nothing to do with Travis, your package is broken.

Also `devtools::check()` is not running tests if they are commented out and will not pass if you uncomment the line.

**Comment by alexWhitworth** [comment]
Quite frankly, I think you're wrong. The tests and R CMD CHECK run perfectly fine on multiple different machines when run locally regardless of whether I comment in/out that line. 

It has to do with [this error](http://stackoverflow.com/questions/38836341/parallelclusterexport-non-exported-library-package-function) and can be completely isolated as such.

**Comment by anirudhacharya** [comment]
@alexWhitworth were you able to resolve the above issue? I am using `covr` and running `package_coverage` returns 0% coverage for certanin .R files even though I have unit tests for those files.

**Comment by alexWhitworth** [comment]
@anirudhacharya It's been awhile... But I believe that's the [commit above](https://github.com/alexWhitworth/imputeMulti/pull/1) that @jimhester provided to my package! So, yes -- [coveralls link](https://coveralls.io/github/alexWhitworth/imputeMulti)

**Comment by anirudhacharya** [comment]
@alexWhitworth I am using `codecov` and not `coveralla`? and I am not able to figure out why coverage report shows 0%. Roughly this is what I am doing -
```
R CMD INSTALL R-package
Rscript -e 'library(testthat);res<-test_dir("R-package/tests/testthat")'
Rscript -e 'library(covr); package_coverage("R-package")'
```
