### ISSUE TITLE
Switch + tryCatch coverage missing

### ISSUE THREAD

**Issue by doug-friedman** [jimhester/covr#264]
I am using switch with a series of tryCatch statements and I _believe_ covr is recording the test coverage incorrectly. It reports that switch is being called 60 times and that the first conditional statement is being called 24 times. However, the 36 other calls to the subsequent conditional statements are not being recorded.

Here's a link to the piece of code via CodeCov.io - https://codecov.io/gh/doug-friedman/SPEI/src/b07ef4581ebddfc269e6ac5f132141859d39d988/R/spei.R#L368

I tested everything manually (and via testthat) to verify that the switch statement works as intended so I _think_ it's a covr issue. However, it's very likely that I'm also doing something wrong. 

Regardless, thanks in advance for taking a look at this.

**Comment by elinw** [comment]
I think https://github.com/jimhester/covr/issues/182  is related (along with a number of other issues), and I'll just add a comment here as well.  I have a list of functions and they always show as uncovered even though they are all explicitly covered.   I'm thinking that if it can't be managed to record running them they could have a different color.

**Comment by doug-friedman** [comment]
Ok. Thanks!

**Comment by elinw** [comment]
Strangely if I do test_files() rather than test_package() the coverage totally changes to include the functions in the list.

**Comment by jimhester** [comment]
The way that covr tracks switch statements does not work if the results are being assigned, as you are doing in the example code.

A workaround is to use braces `{}` around the conditions in the switch, which will then be covered.
