### ISSUE TITLE
Possibility to exclude a test from package_coverage() or to know we are in coverage mode

### ISSUE THREAD

**Issue by BenoitLondon** [jimhester/covr#268]
Hi Jim, great package!

I use package_coverage a lot and I have tests that require the timing of a function being less than some value. Those tests pass in test but fail in covr as I guess the code is not optimized and slowed down by the coverage code.

Is there a way to fix that behavior?

My first guess would be to exclude the test that check the timing but exclusions do not apply on tests AFAIU,another option would be to change the test when we are in coverage mode (like increasing the maximal time allowed if some environment variable R_COVR is set to TRUE)

Any idea if any is doable in the current code or does it need some changes to covr?

Cheers,
Benoit

**Comment by jimhester** [comment]
covr 3.0.0 (just released to CRAN) now sets `R_COVR` when it is running.

However testing the time taken by a command is not a good idea and is explicitly warned against in [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-portable-packages).

> It is not reasonable to test the time taken by a command: you cannot know how fast or how heavily loaded an R platform might be. At best you can test a ratio of times, and even that is fraught with difficulties.

I would suggest you remove such tests from your package.
