### ISSUE TITLE
set_makevars()/reset_makevars() are not parallel safe

### ISSUE THREAD

**Issue by HenrikBengtsson** [jimhester/covr#27]
If multiple `covr` sessions are used in parallel (which may not be unlikely on server farms), there is a risk that '~/.R/Makevars' is being rewritten while another R session is reading it leading to a potentially corrupt read.

One way to lower the risk for this is to have `set_makevars()` only modify '~/.R/Makevars' **iff** the content actually changes, i.e. only call `writeLines(..., lines)` if `lines` have changed from the originally read one.  

This solution does not fully cover the case when a pre-existing '~/.R/Makevars' is **changed**, because then `reset_makevars()` in one session will undo what another session might have written.  However, by only rewriting/undoing the file if something changes the risk for incorrect content is lowered.

The long-term solution is probably for R to provide a command-line option/system environment variable where one can specify a session-specific 'Makevars' file path.

**Comment by jimhester** [comment]
Yes as you said I would definitely prefer to do away with the whole `~/.R/Makevars` situation.  In my opinion setting the appropriate environment variable (CFLAGS ect) should override Rs defaults and that would fix this situation.

Actually getting this changed in R might be impossible though so we should probably implement what you suggest.
