### ISSUE TITLE
Package containing git2r functions in test suite

### ISSUE THREAD

**Issue by MansMeg** [jimhester/covr#276]
Hi!

Thanks for a great package! I just have a short question that I could not find an answer to. I have a package with functions that takes the git hash and store it in a log file that I want to test. Everything works fine with the tests on Travis. But the covr::coveralls() functionality seem to run the tests again in a temp folder that is not a part of the git repository so it fails the tests.

Is there a way to solve this (by forcing where the testsuite is run as an example)?

```
Rscript -e 'covr::coveralls()'
Error: Failure in `/tmp/RtmpYlXtN6/R_LIBS349d50cea840/MyRpackage/MyRpackage-tests/testthat.Rout.fail`
> library(testthat)
> library(MyRpackage)
> 
> test_check("MyRpackage")
1. Error:  (@test-api-put_prospecting_leads.R#9) -------------------------------
The 'path' is not in a git repository
1: expect_message(put_prospecting_leads(lead_data, cfg)) at testthat/test-api-put_prospecting_leads.R:9
2: capture_messages(object)
3: withCallingHandlers(code, message = function(condition) {
       out$push(condition)
       invokeRestart("muffleMessage")
   })
4: put_prospecting_leads(lead_data, cfg)
5: get_git_sha1()
6: git2r::repository(repo, discover = TRUE)
7: git2r::repository(repo, discover = TRUE)
8: .local(path, ...)
9: stop("The 'path' is not in a git repository")
```

**Comment by jimhester** [comment]
No there is no way to solve this. You cannot assume your tests will be run in a git repository, they will not be on CRAN for instance or on users machines who install your package.

You will need to skip these tests if they are run outside a git repository.

**Comment by MansMeg** [comment]
Thank you for the fast reply!

You are definitely right that I can't assume that in general. This is though an internal package that only will be run from within a git repository. I have tests to check for running both inside and outside a repository and would like to test that. 

I think I will solve this as you suggest. I also just realized that it should work if I install the package in a subfolder of the repository and then test that installed package with `covr::coveralls()` that should do what I want.
