### ISSUE TITLE
Covr altering RC objects.

### ISSUE THREAD

**Issue by ocschwar** [jimhester/covr#281]
I have an R codebase that stores a lot of data in RDS files containing reference class objects. When I run it with covr, I discover that covr alters them in a way that breaks how they're used later. The problem applies to files containing my employer's secret sauce, so I'll need a few hours to write a demonstration example: 

`> foo <- readRDS('/home/omri/data/SecretSauce/Seekrit.rds')
> 
> attr(foo,'class') 
[1] "Seekrit"
attr(,"package")
[1] "2017-08-24 22:06:05"
> attr(attr(foo,'class'),'package' )
[1] "2017-08-24 22:06:05"
` 

The class attribute gets a secondary attribute, which has to be removed before I can use the object in the file the way I normally do. 

This removes it: `attr(foo,'class') <- attr(foo,'class')[1]`

Is there a way to prevent this? Thanks!

**Comment by ocschwar** [comment]
Now that I've read the vignettes, I see it's because of the tempdir in which the tests are run. Testing a diff that reads the package name and uses it for a subdirectory in the tmp directory.

**Comment by ocschwar** [comment]
All I needed to do. Now I just need to figure out if it is the prudent thing to do. Perhaps as an optional function argument? 

`
diff --git a/R/covr.R b/R/covr.R
index 1792658..f726e75 100644
--- a/R/covr.R
+++ b/R/covr.R
@@ -219,7 +219,9 @@ package_coverage <- function(path = ".",
 
   tmp_lib <- temp_file("R_LIBS")
   dir.create(tmp_lib)
-
+  tmp_pkg <- paste0(tmp_lib, '/', pkg$package)
+  dir.create(tmp_pkg)
+  
   flags <- getOption("covr.flags")
 
   # check for compiler
@@ -251,7 +253,7 @@ package_coverage <- function(path = ".",
   # install the package in a temporary directory
   withr::with_makevars(flags, assignment = "+=",
     utils::install.packages(repos = NULL,
-                            lib = tmp_lib,
+                            lib = tmp_pkg,
                             pkg$path,
                             type = "source",
                             INSTALL_opts = c("--example",
@@ -261,10 +263,10 @@ package_coverage <- function(path = ".",
                             quiet = quiet))
 
   # add hooks to the package startup
-  add_hooks(pkg$package, tmp_lib,
+  add_hooks(pkg$package, tmp_pkg,
     fix_mcexit = should_enable_parallel_mcexit_fix(pkg))
 
-  libs <- env_path(tmp_lib, .libPaths())
+  libs <- env_path(tmp_pkg, .libPaths())
 
   withr::with_envvar(
     c(R_DEFAULT_PACKAGES = "datasets,utils,grDevices,graphics,stats,methods",
@@ -277,23 +279,23 @@ package_coverage <- function(path = ".",
     withCallingHandlers({
       if ("vignettes" %in% type) {
         type <- type[type != "vignettes"]
-        run_vignettes(pkg, tmp_lib)
+        run_vignettes(pkg, tmp_pkg)
       }
 
-      out_dir <- file.path(tmp_lib, pkg$package)
+      out_dir <- file.path(tmp_pkg, pkg$package)
       if ("examples" %in% type) {
         type <- type[type != "examples"]
         # testInstalledPackage explicitly sets R_LIBS="" on windows, and does
         # not restore it after, so we need to reset it ourselves.
         withr::with_envvar(c(R_LIBS = Sys.getenv("R_LIBS")), {
-          result <- tools::testInstalledPackage(pkg$package, outDir = out_dir, types = "examples", lib.loc = tmp_lib, ...)
+          result <- tools::testInstalledPackage(pkg$package, outDir = out_dir, types = "examples", lib.loc = tmp_pkg, ...)
           if (result != 0L) {
             show_failures(out_dir)
           }
         })
       }
       if ("tests" %in% type) {
-        result <- tools::testInstalledPackage(pkg$package, outDir = out_dir, types = "tests", lib.loc = tmp_lib, ...)
+        result <- tools::testInstalledPackage(pkg$package, outDir = out_dir, types = "tests", lib.loc = tmp_pkg, ...)
         if (result != 0L) {
           show_failures(out_dir)
         }
@@ -301,14 +303,14 @@ package_coverage <- function(path = ".",
 
       # We always run the commands file (even if empty) to load the package and
       # initialize all the counters to 0.
-      run_commands(pkg, tmp_lib, code)
+      run_commands(pkg, tmp_pkg, code)
     },
     message = function(e) if (quiet) invokeRestart("muffleMessage") else e,
     warning = function(e) if (quiet) invokeRestart("muffleWarning") else e)
     })
 
   # read tracing files
-  trace_files <- list.files(path = tmp_lib, pattern = "^covr_trace_[^/]+$", full.names = TRUE)
+  trace_files <- list.files(path = tmp_pkg, pattern = "^covr_trace_[^/]+$", full.names = TRUE)
   coverage <- merge_coverage(trace_files)
   if (!uses_icc()) {
     res <- run_gcov(pkg$path, quiet = quiet)

`

**Comment by jimhester** [comment]
I think the issue is in the assumptions your package code is making, not in covr. You should not be assuming the tests will be run within the package directory.
