### ISSUE TITLE
Missing .gcov files

### ISSUE THREAD

**Issue by jonclayden** [jimhester/covr#33]
Hi Jim,

I've tried out the latest version of `covr` on my `ore` package, and I see

```
> package_coverage()
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/Users/jon/Development/Git/ore/src/onig/enc/ascii.c.gcov': No such file or directory
> traceback()
7: file(con, "r")
6: readLines(file)
5: parse_gcov(paste0(file, ".gcov"))
4: FUN(c("/Users/jon/Development/Git/ore/src/main.c", 
<snip>
   "/Users/jon/Development/Git/ore/src/onig/regversion.c", "/Users/jon/Development/Git/ore/src/onig/st.c"
   )[[2L]], ...)
3: lapply(sources, run_gcov)
2: unlist(lapply(sources, run_gcov))
1: package_coverage()
```

I don't think this is related to #24, even though the error is superficially similar. I see `.gcda` and `.gcno` files in the hierarchy, but no `.gcov` files. This is OS X 10.10.1, with self-built R 3.1.2.

Apologies if I've missed something obvious.

**Comment by jimhester** [comment]
Could you check if you have `gcov` in your path.  I am guessing that the call to gcov failed.

**Comment by jimhester** [comment]
actually I was just able to reproduce something similar on my machine.  I think it may be due to your package having files in subdirectories of src.

I will investigate more.

**Comment by jonclayden** [comment]
Yes, for clarity, `gcov` is on the path, although it seems to really be `llvm-cov` in disguise. The man page does say that "it is compatible with the `gcov` tool from version 4.2 of GCC and may also be compatible with some later versions of `gcov`".

**Comment by jimhester** [comment]
So it looks like gcov needs to be run in the base directory the sources are compiled in, which should always be `src` for R packages, I incorrectly assumed it had to be in the same directory as each source file it was run on.

**Comment by jonclayden** [comment]
Ah, I see. Well, at least that sounds easy to correct!

**Comment by jimhester** [comment]
@jonclayden try with the latest github version it should work with `ore` now (at least it does on my machine).

Thank you for opening the issue!
