### ISSUE TITLE
Race condition when pushing before coverage has been reported

### ISSUE THREAD

**Issue by krlmlr** [jimhester/covr#37]
See the comments by Coveralls in https://github.com/grake/grake/pull/4. The increase in coverage for c59c498 has been reported twice, while that for 3480d2c, the previous commit, hasn't been reported at all. I haven't investigated this further.

**Comment by jimhester** [comment]
Seems to be a bug in how coveralls interacts with the github api, it looks like the jobs were submitted to coveralls correctly by `covr`, https://coveralls.io/jobs/4110439, https://coveralls.io/jobs/4110523, but it must be only looking at the latest completed job when commenting on the pull request (I am guessing).

You could try upstreaming this issue at https://github.com/lemurheavy/coveralls-public/issues

**Comment by krlmlr** [comment]
@jimhester: Thanks for your quick reply, looks like it's not `covr`'s fault.

@lemurheavy: Could you please comment on this race condition?
