### ISSUE TITLE
Coverage on .onAttach(), .onLoad(), .onUnload()?

### ISSUE THREAD

**Issue by HenrikBengtsson** [jimhester/covr#40]
Is it possible to get coverage on `.onLoad()` and similar functions?  I've tried, but get zero coverage for all those.

EDIT: I eventually got `.onUnload()` covered (https://coveralls.io/files/438500374), but I do get zero coverage on `.onAttach()`.

**Comment by jimhester** [comment]
Just call the functions directly in one of your tests (mocking out any functionality you don't want to run), or use the new exclusion mechanisms to exclude those functions from the coverage results.

**Comment by HenrikBengtsson** [comment]
Calling `.onAttach()` may be ok is some cases, but in other cases it should really be called once at startup.  One can of course protect against repeated calls, but that seems like a hack.

I also posted because I wondered why those functions are not covered by default.  Could it be because the package is loaded before `package_coverage()` comes into play?  I can also _imagine_ that `devtools` et al. may not emulate package loading perfectly and that's why it's missed.

Great to see you added support for manual exclusions.  If someone else finds this thread, here's an example:
```r
## Don't report on lines 3-6 in R/000.R and none of the lines in R/zzz.R
excl <- list("R/000.R"=3:6, "R/zzz.R"=1:1e6)
coverage <- covr::package_coverage(exclusions=excl)
```

**Comment by jimhester** [comment]
`devtools::load_all()` does run the package hooks, however the tracing to track test coverage is not added until after the package is loaded with `load_all()`.

Typically the package to be tested is already loaded before the tests are run, so unless you call the hook functions again in your tests they wouldn't be tested anyway.

I think testing the hook functions directly is the correct solution to this (mocking away functionality that should not be done twice).
