### ISSUE TITLE
display coverage results using Rstudio marker API

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#43]
Ala Jimhester/Lintr#37

Would be nice to report only the blank lines

**Comment by piccolbo** [comment]
quickcheck added this or similar feature (which belongs in covr really) but we used html and browseURL. Sure RStudio integration would look sleeker, but then what if people are using something else?

**Comment by jimhester** [comment]
Well we have the interactive shiny app to view results in covr, so this
isn't very high priority since you can use that.  Maybe the readme is
unclear in that regard however.

**Comment by piccolbo** [comment]
didn't know that, will check it out.

**Comment by jimhester** [comment]
Closed by bde4990af12adbdb42c36594189c8a2db69681b0

**Comment by briatte** [comment]
Hi,

Is there a way to disable the use of the source marker API from within `function_coverage` and/or `zero_coverage`?

Using RStudio 0.99.486/Mac. `rstudioapi::hasFun("sourceMarkers")` returns `TRUE`, but I never see any markers, so I'd be interested in a way to get the same output as I get outside of RStudio for `zero_coverage`.

**Comment by jimhester** [comment]
@briatte Yes you can set `options("covr.rstudio_source_markers" = FALSE)` and that should disable them.

More concerning to me is the fact that you don't see any markers, there may be a bug. Can you open a new issue (with an example package which does not produce markers (but should)).
