### ISSUE TITLE
Handle primitive functions and functions with a NULL environment

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#48]
as of #47 these are being skipped, but it would be better track these functions as well.

**Comment by renkun-ken** [comment]
One way to track these functions is to artificially construct a non-primitive wrapper function of the primitive function, but this seems a bit tricky.

**Comment by jimhester** [comment]
If I remember correctly aliases to primitive functions generate a NOTE from `R CMD check` so you have to use a wrapper function to avoid that anyway.

Still I would like to be able to handle primitive functions appropriately regardless.

**Comment by renkun-ken** [comment]
@jimhester, a function that aliases to a primitive function but is not exported will not be marked NOTE, (my package does so ;) but all un-exported functions are transformed by covr, which would result in error if primitive functions were not skipped.
