### ISSUE TITLE
Functions calculated as closures are not covered

### ISSUE THREAD

**Issue by renkun-ken** [jimhester/covr#50]
From my package, it seems that package functions constructed by an internal meta-function is not traced. For example,

```r
function_builder <- function(x) {
  function(a) {
    x + a
  }
}}

#' @export
useful_function1 <- function_builder(1)
#' @export
useful_function2 <- function_builder(2)
```

Even if `useful_function1` and `useful_function2` are both called in tests, the closure `function(a) { x + a }` is always reported not covered.

Example is here:
The code in red https://coveralls.io/builds/1833742/source?filename=.%2FR%2Fpipe.R#L183 is actually called test https://github.com/renkun-ken/pipeR/blob/master/tests/testthat/test2-Pipe.R#L64

**Comment by jimhester** [comment]
This is actually working correctly, if counter-intuitively.  The code you note is uncovered is the code to generate the function, `Pipe_set_function` which is never called in your tests, only on package load.  In particular the code in the resulting functions is actually a copy of the code in the generating function and is tracked separately (This is related to https://github.com/jimhester/covr/pull/25 in that the code that _is_ covered has a srcfile that is an environment).

**Comment by renkun-ken** [comment]
Yes, thanks. Is there a way to cover such package-loading functions?

**Comment by jimhester** [comment]
I guess you have two options.

1. Call `Pipe_set_function` in one of your tests and test that it properly sets a function.  In this case the function should work like any other function.
2. Exclude `Pipe_set_function` from coverage by adding a `# nocov start`, `# nocov end` around the functions

**Comment by renkun-ken** [comment]
Thanks for your suggestions!
