### ISSUE TITLE
Coverage of examples

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#51]
Many packages don't have any tests, but often still have examples.  Would be useful to see what code is covered by examples at least.

**Comment by cboettig** [comment]
+1

**Comment by jennybc** [comment]
I think this is a great idea. In addition to reporting a percentage, will this also leave behind a list of un-exampled functions?

**Comment by jimhester** [comment]
Well right now all coverage is by expression/line so you would have to do the aggregation by function after the fact.
Adding summary by function is on the TODO list (#60) as well however.
I also want to get a shiny viewer (#53) written so it is easy to see what parts are missing coverage.   This is not as big a deal for test coverage with coveralls.io, but for this and #52 we need an offline viewer.

I will try to get this done sooner rather than later since you would find it useful!

**Comment by jennybc** [comment]
In today's twitter conversation, Gabe Becker @gmbecker contributed this snippet, in case it is helpful:

```r
rd = parse_Rd(file)
any(sapply(rd, function(x) attr(x,"Rd_tag") == "\\examples"))
```

**Comment by vnijs** [comment]
@hadley added [test_examples](https://github.com/hadley/testthat/blob/a9bf21a198e9caf5d9fe0e25cfc285bb5c6b0f9f/R/test-example.R)  to testthat. It works with covr and gives a nice boost to my coverage numbers :)

When using test_examples with covr however I do get an 'Error : testthat unit tests failed' message and that does happen when running tests normally. Also, interactive tests that are not run when using R CMD check are run when called through covr which I think might be reason for my failed attempt to use coveralls (i.e., I got a 0% coverage result which is not correct even without the inflated numbers from using run_examples).

**Comment by jimhester** [comment]
I would not recommend using that function with covr as it only tests that the examples run without error (which R CMD check does anyway).  It also does not let you know if a given line is covered only with an example or with tests.

covr has had the ability to run examples for a little while now

```r
# only tests
package_coverage()

# only examples
package_coverage(type="example")

# only vignettes
package_coverage(type="example")

# tests, examples, vignettes
package_coverage(type="all")
```
I haven't closed this issue yet because I wanted to add the ability to view each type of coverage to the shiny app to make it easy to browse and toggle the type of coverage.

It sounds like your package has an issue running tests with covr unrelated to the examples.  Please open a new issue with details of the package and a link to the CI results and I can look into it.

**Comment by vnijs** [comment]
Agreed. Wasn't aware of the `type` option. I filed a request/issue for testthat to capture and compare the examples output to a previous run saved to file (see link below). There is apparently a way to do this with R CMD check but it is not clear how to best capture the output (e.g., plots).

https://github.com/hadley/testthat/issues/255

**Comment by jimhester** [comment]
You can now view the results in an interactive shiny app so you can toggle between the various types with

```r
# tests, examples, vignettes
cov <- package_coverage(type="all")

shine(cov)
```

**Comment by vnijs** [comment]
Fantastic feature! Thanks @jimhester
