### ISSUE TITLE
Coverage of vignettes

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#52]
Along with https://github.com/jimhester/covr/issues/51, it would be handy to report of coverage of vignettes separately as well.

**Comment by cboettig** [comment]
Yup, would be great to see this as a separate section (more as a test of the documentation coverage provided by vignettes than a test coverage, but still handy).

**Comment by gmbecker** [comment]
@jimhester @cboettig 
Code sketch for basic vignette coverage: https://gist.github.com/gmbecker/a1d6ce1e54ef24b194bf

cc @jennybc

**Comment by jimhester** [comment]
As of 24f72ed57a7a1d9d80f28b2062a88e69166de42d you can now do the following

```r
# only tests
package_coverage()

# only examples
package_coverage(type="example")

# only vignettes
package_coverage(type="example")

# tests, examples, vignettes
package_coverage(type="all")
```
And then view the results with the ability to toggle between the various types with

```r
# tests, examples, vignettes
cov <- package_coverage(type="all")

shine(cov)
```
