### ISSUE TITLE
Shiny app to view coverage results.

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#53]
Ideal features would be

Must haves
- [x] select multiple files
- [x] highlight lines that are not covered

Like to haves
- [ ] Select files using file system tree
- [x] Count of line coverage for each covered line
- [ ] Toggle between test/example/vignette coverage

Does not need to track coverage over time as that is what coveralls.io is mainly for.

**Comment by jimhester** [comment]
work on this is in https://github.com/jimhester/covr/tree/shiny

**Comment by jennybc** [comment]
Do you have any plans to implement this such that `shiny` is suggested but not required? It seems odd that `shiny` is required to, e.g., assess my test coverage on travis.

**Comment by jimhester** [comment]
You are right, I will put it Suggests and load if needed.  Thank you for
the suggestion
