### ISSUE TITLE
coverall Error: No description at /home/travis/build/$USER/DESCRIPTION

### ISSUE THREAD

**Issue by armaneshaghi** [jimhester/covr#55]
We get the following error after successful build with travis:

`Error: No description at /home/travis/build/stnava/DESCRIPTION`

The complete travis log file, associated with this error is:

```
* help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (ANTsR)

The command "R CMD INSTALL ANTsR" exited with 0.
$ Rscript -e 'library(covr);coveralls()'
Loading required package: methods
Error: No description at /home/travis/build/stnava/DESCRIPTION
Execution halted

Done. Your build exited with 0.
```

This is our `.travis.yml` [here](https://github.com/stnava/ANTsR/blob/master/.travis.yml). I would appreciate any comments on this.

PS The coverage after this error remains "unknown"

**Comment by stnava** [comment]
this is because the coverage command needs to be called from within the package source ... 

cd ANTsR 

then Rscript etc resolves it ...  but it's long running so still times out

**Comment by jimhester** [comment]
`coveralls()` does not have to be run in the package directory, but if it is not you have to give it the proper path _to_ that directory.  See the `path` argument in `?coveralls`

**Comment by stnava** [comment]
yes - should have written "the coverage command w/no arguments"
