### ISSUE TITLE
Coverage fails on compiled code coverage.

### ISSUE THREAD

**Issue by ehrlinger** [jimhester/covr#56]
I'm working on a package with compiled code. It builds fine, but fails when I run:

``` {R }
> Rscript -e "library(covr);package_coverage()"
Loading required package: methods
rfsrc tests : 

Unexpected version: *904.
Invalid .gcno File!
.
.
.
Unexpected version: *904.
Invalid .gcno File!
Error in names(res) <- file.path(src_path, names(res)) : 
  attempt to set an attribute on NULL
Calls: package_coverage -> run_gcov
Execution halted
```

This happens locally on OS X. 

It fails on the TravisCI Linux server as well:
``` 
Error in seq.default(df[i, "first_line"], df[i, "last_line"]) : 
  'from' cannot be NA, NaN or infinite
Calls: coveralls -> to_coveralls -> per_line -> seq -> seq.default
Execution halted
```

**Comment by ehrlinger** [comment]
Scratch the TravisCI issue. It just completed fine.

**Comment by jimhester** [comment]
The first error is due to an incompatibility in the gcov format produced by your compiler and the gcov program on your path.  I would guess that it is compiling with gcc but trying to use the clang gcov, or vise versa.

**Comment by ehrlinger** [comment]
Alright, If I can get coverage through TravisCI -> Coveralls, I’m happy.

I’ll poke around to see why it would try to use gov with clang. I’m sure my code was gcc compiled.

Thanks.

**Comment by jimhester** [comment]
Run `gcov --version` and see if it is the GCC gcov or the clang version.  I am guessing that the clang version is first on your path.

**Comment by ehrlinger** [comment]
That is correct. Now where would I find the gcc gcov…

**Comment by ehrlinger** [comment]
More information on this issue, on linux systems

package_coverage() works fine,
coveralls() fails with the error stated

On OS X, I guess there is not a gcc gcov implementation. For my particular package, there is not a clang openMP implementation. So I'll have to compile this special for code coverage using OSX platform. I'll give that a shot.

**Comment by jimhester** [comment]
Make sure there isn't a `gcov` already in your `gcc` bin directory.  I no longer have access to an OSX machine, but when I did I had both a gcc gcov and a clang one.

```bash
mdfind -name gcov
```

Should find both versions, you just have to ensure that the gcc gcov is included in your path before the clang one.

**Comment by ehrlinger** [comment]
Got a way to rename the gcov application by name? Then I could use `gcov-4.9` instead of `gcov`

**Comment by jimhester** [comment]
Nope, just modify your `PATH` environment variable so that `gcov-4.9` (symlinked to `gcov` if necessary) comes before the system `gcov`.

**Comment by ehrlinger** [comment]
OK. That worked. THX.

Still getting the message from the `coveralls` command 
```
Error in seq.default(df[i, "first_line"], df[i, "last_line"]) : 
  'from' cannot be NA, NaN or infinite
```

`package_coverage()` completes as expected.

**Comment by ehrlinger** [comment]
Should have thought of this earlier...

```
 traceback()
5: stop("'from' cannot be NA, NaN or infinite")
4: seq.default(df[i, "first_line"], df[i, "last_line"])
3: seq(df[i, "first_line"], df[i, "last_line"])
2: per_line(x)
1: covr:::to_coveralls(package_coverage())
```

**Comment by jimhester** [comment]
@ehrlinger Does this issue still occur with the current HEAD?
