### ISSUE TITLE
handling tests skipped by testthat::skip ?

### ISSUE THREAD

**Issue by cboettig** [jimhester/covr#58]
I think `covr` should have the option of not reporting test coverage if any test has been skipped by `testthat::skip`.  

I tend to use the skip function only when a test depends on some external web resource that might not be available.  `testthat:skip` allows intermittent failures to reach that external web resource without the red warning signs of a failed test.  If the tests are being skipped on a particular build because the resource was unavailable, it does not seem reasonable for the coverage to drop instead of just remaining at what it's last value was.  

Not actually sure how to go about this. Would have to dig into @hadley's testthat code to see if `skip` is giving any other programmatic indication that a test has been skipped, other than the visual printing `S` instead of `.` where the test has would have been run in the `testthat` summary.

**Comment by jimhester** [comment]
>  it does not seem reasonable for the coverage to drop instead of just remaining at what it's last value was.

The fact that you are talking about temporal coverage suggests to me that you are submitting multiple builds of the same commit to `coveralls.io`.  `covr` has no concept of coverage over time, i.e. there is no way to track what the previous coverage was, so we are not going to be able to handle this case.

What I would suggest is to limit the `covr` run to only one specific build environment using a conditional and only submit one coverage result per commit.

The other option is to open an issue at https://github.com/lemurheavy/coveralls-public/issues to always take the maximum coverage from all reports based on a given commit (which seems like reasonable behavior to me).

**Comment by cboettig** [comment]
@jimhester Sorry if I was confusing, no I'm not talking about any kind of multiple builds; just super basic vanilla stuff.   I was simply referring to coverage dropping on _different_ consecutive commits, not due to any changes in the R code or the tests themselves, but due to a test just happening to be skipped because just by chance, the external resource that test depended on was not available. 

With the current implementation of covr, the coverage does drop on this later commit, because the test under `skip` control is not run.  Does that make sense?

**Comment by jimhester** [comment]
That makes sense, however there is still nothing really to be done for this case.  As I said above we never store the coverage from previous runs, so there is no way to use the previous coverage.

You could write a function that took the previous coverage results and the current coverage results and returned the maximum coverage between the two of them, but beyond that I think you are stuck.

Even if there was a way to figure out what tests were skipped what you really need to know is what code would have been run if they were _not_ skipped and there is no way to do that without running the code.

**Comment by cboettig** [comment]
Hi Jim, thanks for the reply.  I was thinking of a much simpler workflow in
which covr would simply not send data to coveralls.io if tests had been
skipped, just as currently no data is sent if tests fail. The trick would
simply be for the `coveralls()` function to detect if any tests had been
skipped.  Does that make any sense or am I missing something here?

**Comment by jimhester** [comment]
Ah this does make sense now.

I think the best place for this might actually be in `testthat` itself.  Maybe it should set something similar to `.Last.value` with the results of the previous tests run that can be checked afterwards.

`covr` simply sources the `test` directory to run the tests, so it has no knowledge of what testing infrastructure is used (and should be compatible with all of them).

`testthat::test_dir` does return a `data.frame` of the tests results, although looking at the output briefly it does not look like there is a column indicating if a given record is skipped.

**Comment by jimhester** [comment]
@cboettig `testthat::test_dir()` should be returning the skipped tests as a column, so you should be able to use that information to test if you want to submit to coveralls or not.  Maybe the easiest way to do so is

```r
library(testthat)
cov <- package_coverage(".", type = "none",  res <- testthat::test_dir("tests/testthat"))

if (any(as.data.frame(res)$skipped)) {
  coveralls(coverage = cov)
}
```

**Comment by cboettig** [comment]
nice, thanks!
