### ISSUE TITLE
Functionality to disable/enable coverage

### ISSUE THREAD

**Issue by RomanTsegelskyi** [jimhester/covr#71]
Thanks for great work on the package. I am working on a tools for creating test cases for different VM implementations of R (https://github.com/allr/testr). Part of it does filtering based on code coverage and I was thinking to use `covr` for it. However, since I am trying to measure coverage for functions in `base` namespace, I was wondering if it would be possible to add hooks to disable/enable counting, so `covr` code coverage does not interfere with test cases code coverage.

So in the end, I will be able to run something like that

``` r
expect_equal({cov:::enable(); 
              res <- test_case_code; 
              cov:::disable(); 
              res}, 
             expected)
```

I would add that as a pull request, but I was wondering if you will accept that functionality and how to add it since there are no global option in `covr`?

Should it be something like

``` r
.enabled <- TRUE
disable <- function() .enabled <<- FALSE
enable <- function() .enabled <<- TRUE

count <- function(key) {
  if (.enabled)
  .counters[[key]] <- .counters[[key]] + 1
}
```

**Comment by jimhester** [comment]
This seems reasonable, I would prefer to wait until I have a proper configuration setup for `covr`.  I recently wrote one for `lintr` that should be fairly straightforward to reuse, so we could use that here.

**Comment by jimhester** [comment]
I unfortunately don't have time to work on this feature. However if you are still interested I would be happy to review a PR for it.
