### ISSUE TITLE
Double-run of tests on Travis?

### ISSUE THREAD

**Issue by jennybc** [jimhester/covr#73]
Do I understand this correctly? If I enable test coverage tracking via `covr` in my `.travis.yml` file, every time I build on Travis, my tests will be run a second time?

The reason I ask is that my tests take a while and are against an API that frequently glitches due to a butterfly flapping its wings in China. So I'm not eager to wait it out a second time every time I build on Travis. And I'm not even sure what your package does when tests fail. I already have to manually re-run Travis builds frequently due to the flaky API thing.

Related: `[skip ci]` in a commit message keeps Travis from building. Is there anything analogous for `covr`? I'd like the inverse, actually. I'd like to only run `covr` when I include something like `[covr]` in the commit message.

**Comment by jimhester** [comment]
Yes covr has to run the tests independently of the regular check.  There
isn't any other way to do it unless you want the installed code to be
always instrumented with tracing calls.

If your tests are against a slow and unreliable service out of your control
you probably should be mocking the expected responses in your tests rather
than querying the service directly.  See `testthat:: with_mock` for how to
do this.

You can implement the conditional behavior you describe in your
`.travis.yml` by checking the git commit message in a bash conditional
statement, then only running covr if that statement is true.

**Comment by jennybc** [comment]
Thanks for the info. The whole package is an API wrapper so the mocking strategy makes me want to curl up in a ball. I'm already at ~90% coverage (thanks `covr` for telling me!), so don't really want to dismantle all of that.

Great idea re: what to do on travis re: conditionally running `covr`. I'll try that. Know of any examples offhand w/ conditional execution? Need not even be R / covr related.

**Comment by jennybc** [comment]
These links looks helpful:

http://stackoverflow.com/questions/29082831/perform-after-success-actions-conditionally

https://github.com/twbs/bootstrap/blob/e3f4072a9e1f1163c5b7b6a52d9b2632569f90fb/.travis.yml#L9

https://github.com/travis-ci/travis-ci/issues/2657#issuecomment-51716659

in case anyone else wanders through here.

**Comment by jennybc** [comment]
OK this works:

https://github.com/jennybc/gspreadr/blob/5c3d2ee478feac59ed2cfe933b754889b02cc450/.travis.yml#L25-L26
