### ISSUE TITLE
specifying package folder as "packageName/" does not work

### ISSUE THREAD

**Issue by gonike** [jimhester/covr#75]
Suppose I'm in a directory containing the sources of a package "testpackage" in folder "testpackage/". Running

> package_coverage("testpackage")

works, while running

> package_coverage("testpackage/")

does not. This is quite annoying, since autocompletion in both IDEs that I use (RStudio, ESS) always creates the second version. Moreover, all the devtools functions work with the second option.

**Comment by jimhester** [comment]
You are going to need to provide more information on this.

I cannot reproduce it on my machine in any form, I get the same results regardless of the trailing slash.

Particularly, what OS is this on, what is the error message you receive and what is your working directory.

**Comment by gonike** [comment]
Sorry, should have included that right away. I am on a Windows 7 64-bit machine. The folder `C:/Users/petersee/Documents/Work/testcovr/` contains the package in question.

Hope this helps. Please tell me if you need anything else.

    > getwd()
    [1] "C:/Users/petersee/Documents/Work"
    > package_coverage("testcovr/")
    NULL
    > package_coverage("testcovr")
    doublefun : .
    
    Keep up the good work. 
    Package Coverage: 66.67%
    R/doublefun.r: 66.67%
    > session_info()
    Session info --------------------------------------------------------------------
     setting  value                       
     version  R version 3.1.3 (2015-03-09)
     system   x86_64, mingw32             
     ui       RStudio (0.98.1091)         
     language (EN)                        
     collate  German_Germany.1252         
     tz       Europe/Berlin               
    
    Packages ------------------------------------------------------------------------
     package      * version    date       source                         
     bitops       * 1.0-6      2013-08-17 CRAN (R 3.1.0)                 
     covr           0.2.0.9002 2015-03-31 Github (jimhester/covr@c70153f)
     crayon       * 1.1.0      2014-10-15 CRAN (R 3.1.3)                 
     devtools       1.7.0      2015-01-17 CRAN (R 3.1.3)                 
     evaluate     * 0.5.5      2014-04-29 CRAN (R 3.1.0)                 
     formatR      * 1.1        2015-03-29 CRAN (R 3.1.3)                 
     httr         * 0.6.1      2015-01-01 CRAN (R 3.1.3)                 
     knitr        * 1.9        2015-01-20 CRAN (R 3.1.3)                 
     lazyeval     * 0.1.10     2015-01-02 CRAN (R 3.1.2)                 
     magrittr     * 1.5        2014-11-22 CRAN (R 3.1.2)                 
     plyr         * 1.8.1      2014-02-26 CRAN (R 3.1.1)                 
     Rcpp         * 0.11.5     2015-03-06 CRAN (R 3.1.3)                 
     RCurl        * 1.95-4.5   2014-12-28 CRAN (R 3.1.3)                 
     reshape2       1.4.1      2014-12-06 CRAN (R 3.1.3)                 
     rex          * 0.2.0      2014-11-26 CRAN (R 3.1.3)                 
     roxygen2     * 4.1.0      2014-12-13 CRAN (R 3.1.3)                 
     rstudio      * 0.98.1091  2014-12-02 local                          
     rstudioapi   * 0.2        2014-12-31 CRAN (R 3.1.3)                 
     stringr      * 0.6.2      2012-12-06 CRAN (R 3.1.0)                 
     testcovr       0.0.0.9000 <NA>       local                          
     testRPackage   0.1        <NA>       local                          
     testthat       0.9.1      2014-10-01 CRAN (R 3.1.3)                 
     whisker      * 0.3-2      2013-04-28 CRAN (R 3.1.0)
