### ISSUE TITLE
Changing the default exclusion regexs

### ISSUE THREAD

**Issue by jimhester** [jimhester/covr#79]
@jackwasey, @krlmlr, based on the following github search you are the only people currently using the "EXCLUDE COVERAGE" defaults.

https://github.com/search?p=3&q=language%3Ar+%22EXCLUDE+COVERAGE%22&ref=searchresults&type=Code&utf8=%E2%9C%93

As of ef1f8e0cdb6edbdd94c5959a79b9cd3bea6db412 I am planning on changing these defaults to `# nocov` as the previous defaults were long and kind of obnoxious.

That branch is not merged into trunk yet, but I plan to do so in the near future.

If you want to preserve the previous behavior either pass `exclude="#[[:space:]]*EXCLUDE COVERAGE"` to the call to `package_coverage()` or set `options(covr.exclude = "#[[:space:]]*EXCLUDE COVERAGE")`.  You would have to do the same with the two other exclude search terms as well.

**Comment by jackwasey** [comment]
Thanks for the warning.

**Comment by krlmlr** [comment]
:+1: The worst thing that can happen is that reported coverage drops, and then we remember to update the code. I feel it's ok to go ahead and merge.
