### ISSUE TITLE
Travis failure due to lack of robustr for R version 3.2.0

### ISSUE THREAD

**Issue by jennybc** [jimhester/covr#80]
A Travis build just failed for me like so:

```
ERROR: dependency ‘robustr’ is not available for package ‘covr’
* removing ‘/usr/local/lib/R/site-library/covr’
Error: Command failed (1)
In addition: Warning message:
package ‘robustr’ is not available (for R version 3.2.0) 
Execution halted
The command "./travis-tool.sh github_package jimhester/covr" failed and exited with 1 during .
Your build has been stopped.
```

Does `robustr` need to be updated on CRAN? Or do I have to add this to the list of things I install from GitHub?

**Comment by trinker** [comment]
From what I can tell **robustr** is new and not on CRAN: https://github.com/jimhester/robustr/commits?author=jimhester

Add this to the `travis.yml` before you install *covr**:

```r
  - ./travis-tool.sh github_package jimhester/robustr
```

Jim can you confirm if this is the correct approach?

**Comment by jimhester** [comment]
That is the right approach, I may roll back that merge until robustr is on
CRAN, didn't think about the dependency issue

**Comment by jennybc** [comment]
I did try adding a line to install `robustr` from GitHub, but that build failed too. Maybe it would have worked if I had put the command to install `robustr` __prior__ to the one to install `covr`? I have since deleted that branch …

For now, I just removed the `covr` bits in `.travis.yml` and will restore when this situation has resolved.

Is it possible to specify the commit in this sort of line:

```
  - ./travis-tool.sh github_package jimhester/covr`
```

so I can guard against this sort of thing in future?

**Comment by trinker** [comment]
@jennybc Yeah it has to be prior.  See where I just did this and the error disappeared:

https://raw.githubusercontent.com/trinker/wakefield/master/.travis.yml

**Comment by jennybc** [comment]
OK thanks to you both. That does sort things out.

**Comment by dwinter** [comment]
In case anyone using the 'native' R support for travis hits the same problem, the order of the github packages matters there too (don't ask how long it took me to work this out...)

 So this should get the job done:

```yml
r_github_packages:
    - jimhester/robustr
    - jimhester/covr
```

**Comment by jimhester** [comment]
I have temporarily added the robustr functions to covr so this situation will be resolved until robustr is on CRAN.

I apologize for breaking things, that was not my intent, I try to keep master green as much as possible now that `covr` is being used fairly extensively.

Also @jennybc You should be able to specify a specific SHA1 to install from with `@ref`, so if you wanted to use the version prior to my latest merge you should be able to do (but I have not tested)

```yaml
r_github_packages:
    - jimhester/covr@6394c79848
```

**Comment by jennybc** [comment]
Thanks @jimhester.

Do you plan to submit `covr` to CRAN? And/or tag certain commits as releases or pseudo-releases? I think I might like to install on travis from such a milestone, using the SHA1 method above, instead of always taking the most recent commit from GitHub.

**Comment by jimhester** [comment]
I am going to submit `covr` to CRAN soon.  I just added tags for any commit where I bumped the version, but I cannot say if any of them are more or less reliable than HEAD.

**Comment by trinker** [comment]
This reversion breaks things for me on all my repos and I can't figure out how to fix:

For example in  [qdapRegex](https://travis-ci.org/trinker/qdapRegex) I get the following error with [THIS](https://raw.githubusercontent.com/trinker/qdapRegex/master/.travis.yml) .yml file:

```
Installing GitHub packages: jimhester/covr
+Rscript -e 'library(devtools); library(methods); options(repos=c(CRAN="http://cran.rstudio.com")); install_github(commandArgs(TRUE), build_vignettes = FALSE)' jimhester/covr
Downloading github repo jimhester/covr@master
Error: is.config(config) is not TRUE
Execution halted
The command "./travis-tool.sh github_package jimhester/covr" failed and exited with 1 during .
Your build has been stopped.
``

**Comment by jimhester** [comment]
This is a bug in the devel devtools, it doesn't happen with CRAN devtools.  Please open an issue at https://github.com/hadley/devtools/issues

**Comment by jimhester** [comment]
@trinker I opened an devtools issue about this https://github.com/hadley/devtools/issues/778

**Comment by trinker** [comment]
@jimhester  Thanks for tracking down the issue.
