### ISSUE TITLE
isNamespaceLoaded

### ISSUE THREAD

**Issue by aaronbenz** [jimhester/covr#85]
isNamespaceLoaded() is in 3.2 but not in 3.1 although it claims support for 3.1 correct? When trying to use I am getting an error in 3.1 because isNamespaceLoaded() does not exist...

I could create a small pull request to have isNamespaceLoaded <- function(x) x %in% loadedNamespaces() if it is in 3.1.... or am I missing something?

**Comment by jimhester** [comment]
You are correct, my apologies!  Probably

```r
if (getRversion() < "3.2.0") {
  isNamespaceLoaded <- function(x) x %in% loadedNamespaces()
}
```

In `utils.R` should work I think
