### ISSUE TITLE
package data not found - works fine with R CMD check

### ISSUE THREAD

**Issue by vnijs** [jimhester/covr#86]
First: Awesome tool!! The shiny app that shows which lines are not yet tested is wonderful. Looking forward to getting example testing working as well. Question: Is break-down in examples vs tests likely to work (at some point) with Travis / Coveralls as well?

Second: When trying cov <- package_coverage(type="example") I get the error below. mp3 is a file in data/ and works fine with tests when running R CMD check. Repo here: https://github.com/vnijs/radiant. I run the code using file coverage.R in the root directory of the repo.

The error message is coming from function getdata in R/radiant.R that is being called by the test in R/conjoint.R for function conjoint

`Dataset mp3 is not available. Please load the dataset and use the name in the function call
Error in function_list[[i]](value) : `

**Comment by jimhester** [comment]
Try it with 20a297f3e33  I just ran into this as well.  The issue was the example extraction code did not have a `library()` call on the top, so data files used in examples weren't working.

**Comment by jimhester** [comment]
Also re: examples on coveralls, I doubt it will ever be supported as there is no real analog to example or vignette coverage in other languages.

**Comment by vnijs** [comment]
Making progress ... new error. Presumably when running the examples in man/correlation.Rd

No problems with devtools::run_examples()

Error in set_class(., c("correlation", class(.))) : 
  unused arguments (., c("correlation", class(.)))

re: examples on coveralls. Doesn't python have something like this?

**Comment by jimhester** [comment]
Could you try with 89fd52b094f4279790f41fe5c3577df1e95395ff, I can now run the radiant examples on my machine without error.

It is now running essentially exactly what R CMD check runs for examples, so hopefully there won't be any differences now.

**Comment by vnijs** [comment]
Works like a charm! Thanks @jimhester
