### ISSUE TITLE
Vectorized functions are not covered.

### ISSUE THREAD

**Issue by shabbychef** [jimhester/covr#89]
Functions which are wrapped by a ```Vectorize``` call are not counted in code coverage. I have seen this in [SharpeR](https://github.com/shabbychef/SharpeR/blob/master/R/distributions.r#L690-L735). A MWE might look as follows:
```r
# bad style, but illustrates the point:
scalar_func <- function(x,y) {
  z <- x + y
}
vector_func <- Vectorize(scalar_func,vectorize.args=c("x","y"),SIMPLIFY=TRUE)
```
coverage of ```scalar_func``` will not be reported. (In fact, it is not clear that the definition of ```vector_func``` is reported as covered.)

**Comment by shabbychef** [comment]
For the moment, I am experimenting with `# nocov start` and `# nocov end` blocks to deal with this manually.

**Comment by abelcastilloavant** [comment]
Possibly related: functions wrapped in `memoise::memoise` seem to be skipped altogether: for example, the Codecov report doesn't highlight lines https://github.com/jimhester/covr/blob/master/R/utils.R#L48-L119 at all.

**Comment by jimhester** [comment]
These are both due to the fact that the generated functions don't have srcref attributes attached to each call like the original functions.

This was actually very easy to add once I looked at it, we can simply need to add tracing calls to the stored function definition in both cases.

**Comment by abelcastilloavant** [comment]
Awesome, thanks!

**Comment by shabbychef** [comment]
great!
