### ISSUE TITLE
Rcpp/fortran support?

### ISSUE THREAD

**Issue by hadley** [jimhester/covr#9]
Is there any chance you might be able to combine covr with an existing C++ code coverage tool in order to also give C++ code coverage stats?

**Comment by jimhester** [comment]
Yeah that is something I want to add, I had a few links in #4 about it.  Should be able to use https://gcc.gnu.org/onlinedocs/gcc/Gcov.html with a little work.

**Comment by jimhester** [comment]
@hadley what is the preferred way to pass compiler flags to `devtools::load_all()`?  I tried adding

```r
  old <- devtools:::set_envvar(c(CFLAGS = "-fprofile-arcs -ftest-coverage", CXXFLAGS = "-fprofile-arcs -ftest-coverage", FFLAGS = "-fprofile-arcs -ftest-coverage"), "prefix")
  on.exit(devtools:::set_envvar(old), add = TRUE)
```

before [covr.R#L181](https://github.com/jimhester/covr/blob/5a43a61c84972e5797c0a8d1fedba04d65aaf40c/R/covr.R#L181) which does set `CFLAGS`, `CXXFLAGS`, and `FFLAGS` environment variables, but those values don't seem to be used when compiling.  (The flags from `devtools::compiler_flags()` also seem to be ignored).  I tried compiling `dplyr` and `devtools`, in both cases the environment variables don't seem to be used.

Am I doing something obviously wrong, or is there an alternative method we need to use to force the profiling flags?

**Comment by jimhester** [comment]
the answer to the above is you need to use PKG_CFLAGS PKG_CXXFLAGS etc.  I think this is also a bug in `devtools::compiler_flags()` as well.

**Comment by hadley** [comment]
Do you have latest devtools? There was a problem previously - I'm pretty use `CFLAGS` etc is the right choice because it's for user overrides on the compilation of all packages .`PKG_CFLAGS` etc is for options for a specific package.

**Comment by jimhester** [comment]
`devtools   * 1.6.1.9000 2014-12-30 Github (hadley/devtools@6192843)`

It may be that the packages I have tested against all define `PKG_CFLAGS` variables in `Makevars` so they are overriding the values in `CFLAGS`.  In which case `devtools` is probably ok.

**Comment by jimhester** [comment]
preliminary support is now on master via 572d3da.

Outstanding issues

- [ ] We should probably override complier optimization options to always be `-O0` as lines can get optimized out completely which makes the output hard to interpret.  I need to figure out how to do this though.
- [ ] source files which are not run at all by tests will not get counted as uncovered.

**Comment by jimhester** [comment]
So the only real issue I am running into here is forcing R to use `-O0` when compiling.  From @eddelbuettel's answer at http://stackoverflow.com/a/23414789/2055486 it seems like the only way to override the default `CFLAGS` is by adding values to `~/.R/Makevars`.  Doing that temporarily seems hacky, but I don't really see another way to go unless there is another way to override the values.  Setting the `CFLAGS` environment variable has no effect.

**Comment by eddelbuettel** [comment]
From memory, I may have seen something lately in [R NEWS changes](http://developer.r-project.org/blosxom.cgi/R-devel) (which I read daily via RSS) that they allow overriding now.  Hitherto $RHOME/etc/Makeconf always won making this an issue.  Not really sure if it changed, but may be worth checking with R-devel.

**Comment by jimhester** [comment]
Ok I will look around some more and see if I can find anything, thanks Dirk!

**Comment by jimhester** [comment]
As of 18d92102c05ff0e916b53c9e827ec03b9066809c this is now working locally by using a subprocess R session, but failing when trying to use `R CMD check` or on travis, possibly because of issues mentioned in https://github.com/hadley/testthat/issues/144.  I added `R_TEST="" and NOT_CRAN="true" and it got further, but there is still an issue of some kind.  Will keep trying though!

**Comment by jimhester** [comment]
Ok now seems to be working on everything but `covr` itself.  Here is an example of the digest package.

https://coveralls.io/builds/1749592

**Comment by helske** [comment]
I see that this works for C/C++, but for some reason coveralls does not check the Fortran code in my package: https://coveralls.io/r/helske/KFAS 

I am new to both Travis and Coveralls so it might be just me. Any hints?

**Comment by helske** [comment]
Tested this also locally on Linux, I compiled with `-O0` and changed package `Makevars` to
`PKG_LIBS = $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) -fprofile-arcs`
`PKG_FCFLAGS = -fprofile-arcs -ftest-coverage`

This seems to make the necessary gcov files but `package_coverage` still does not report any info about `.f95` files.

**Comment by jimhester** [comment]
@helske this is because the function used to detect source files does not find extension `.f95` like you used in your project.  https://github.com/jimhester/covr/blob/master/R/compiled.R#L81-L82.  It needs to be updated to handle all of the common FORTRAN extensions, http://fortranwiki.org/fortran/show/File+extensions seems like a decent list.

Right now the only FORTRAN extension that is found is `.f`

**Comment by helske** [comment]
Thanks, should have figured that out by debugging the code a bit. I updated the `compiled` function (and `package_coverage`) accordingly and created a pull request: https://github.com/jimhester/covr/pull/64
