### ISSUE TITLE
What's the preferred installation method in .travis.yml post CRAN release?

### ISSUE THREAD

**Issue by jennybc** [jimhester/covr#96]
Now that `covr` is on CRAN, what's the preferred method of installing `covr` in `.travis.yml`?

**Comment by jimhester** [comment]
I would probably still install the development version personally, but if you want to use the cran version you can use

```yaml
r_packages:
  covr
```

**Comment by jennybc** [comment]
OK thanks. BTW is there a reason for the pivot towards codecov vs coveralls?

**Comment by jimhester** [comment]
I think codecov is a better service, it has more features and is more
responsive to requests, plus the default display is easier to display
coverage.

It also does not default to commenting on every pull request, which
coveralls does.
