### ISSUE TITLE
covr says tests failed

### ISSUE THREAD

**Issue by stephlocke** [jimhester/covr#97]
I'm currently doing some infrastructure work on my package `optiRum`.  I use covr and last build worked fine. That was about a month ago.

Today, I added an additional step to my build to and despite testthat running fine in the check component, covr says the tests failed.
> Error : testthat unit tests failed

[repo](https://github.com/stephlocke/optiRum)
[Travis log](https://travis-ci.org/stephlocke/optiRum/builds/64819627)
[Coveralls job](https://coveralls.io/jobs/6317319)

Running `package_coverage()` locally has all tests passing
```
> package_coverage()
Warning: package 'testthat' was built under R version 3.1.3
Loading required package: optiRum
Warning in dir.create(testpath) :
  'C:\Users\slocke\Documents\optiRum\tests\testthat\temp' already exists
Warning: package 'plyr' was built under R version 3.1.3
Test Coverage: 89.74%
R\multiplot.R: 0.00%
R\calcNetIncome.R: 88.64%
R\APR.R: 100.00%
R\CJ.dt.R: 100.00%
R\convertToXML.R: 100.00%
R\generatePDF.R: 100.00%
R\giniChart.R: 100.00%
R\giniCoef.R: 100.00%
R\logit.odd.R: 100.00%
R\logit.prob.R: 100.00%
R\odd.logit.R: 100.00%
R\odd.prob.R: 100.00%
R\PMT.R: 100.00%
R\pounds.R: 100.00%
R\prob.logit.R: 100.00%
R\prob.odd.R: 100.00%
R\PV.R: 100.00%
R\RATE.R: 100.00%
R\sanitise.R: 100.00%
R\scaledScore.R: 100.00%
R\taxYear.R: 100.00%
R\theme_optimum.R: 100.00%
R\thousands.R: 100.00%
R\wordwrap.R: 100.00%
>
```

I was wondering how I might go about debugging further as running `coveralls()` locally as I get when trying to naively recreate.
> Error in coveralls() : 
>  Failed to upload coverage data. Reply by Coveralls: Couldn't find a repository matching this job.

**Comment by jimhester** [comment]
All `coveralls()` does is run `package_coverage()` internally, so there must be something weird going on on the server that is not replicated in your local environment.

coveralls has an optional `coverage` parameter, so you can run `package_coverage()` first and pass the results to coveralls.  `quiet = FALSE` will display more diagnostic messages when calculating coverage, so hopefully you can figure out the cause.  The below will print the coverage results and submit to coveralls in one step.

```r
coveralls(coverage = print(package_coverage(quiet = FALSE)))
```

**Comment by stephlocke** [comment]
Thanks - that helped!

It looks like a xetex dependency had changed or something

Additionally, the results for those builds did eventually show up
