### ISSUE TITLE
When Sourcing Unparsable Files, There Is No Indication What File Has the Error

### ISSUE THREAD

**Issue by wsloand** [jimhester/covr#98]
This enhancement request is very minor overall, but if there is a possibility to fix it, testing could be easier.

I just forgot a parenthesis in one of my package tests, and I got the following error:

    > mycoverage <- package_coverage()
    Error in parse(n = -1, file = file, srcfile = NULL, keep.source = FALSE) : 
      87:0: unexpected end of input
    85: 
    86: }
       ^
    > traceback()
    No traceback available 

I found the issue was with one of my test scripts, but I had to do that manually.  There was no obvious way to find which file was being run.

**Comment by jimhester** [comment]
This is an unfortunate side effect of having to run the tests in a new process.  If there is an error covr will create a `last.dump.rdata` file, which can be loaded and passed to `debugger()` to give you a traceback of where the execution failed.

**Comment by jimhester** [comment]
I have since reworked the way in which errors are reported, `covr` now simply prints the stack trace of the error, so this should be addressed.  If you still feel it is not adequate please reopen this issue.
